### ISSUE TITLE
Save stdout and stderr to a file, while printing it during runtime

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/e3sm_diags#148]
This helps with the provenance.

**Comment by chengzhuzhang** [comment]
The error logs can be saved in prov folder.

**Comment by tomvothecoder** [comment]
Hey @chengzhuzhang, is the v2.7.0 release candidate phase starting January 1st (1 month before the next E3SM Unified release)? Just checking the priority of this task based on release timelines.

**Comment by chengzhuzhang** [comment]
Yes! Let's git it in for the v2.7.0 release around Jan 1st. Thank you for working on this!
