### ISSUE TITLE
Ability to add variables that are in derived_variables

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/e3sm_diags#162]
I'm new to E3SM-diags and am using it to compare two models.  I wanted to compare the PRECL and PRECC results between the two models.  I added them to a config file following the example online but got the following error:

```
Variable: PRECL
Error in acme_diags.driver.zonal_mean_xy_driver
Traceback (most recent call last):
  File "/export/donahue5/anaconda2/envs/e3sm_diags_env/lib/python2.7/site-packages/acme_diags-1.3.2-py2.7.egg-info/scripts/acme_diags_driver.py", line 78, in run_diag
    single_result = module.run_diag(parameters)
  File "/export/donahue5/anaconda2/envs/e3sm_diags_env/lib/python2.7/site-packages/acme_diags/driver/zonal_mean_xy_driver.py", line 124, in run_diag
    var, acme.derived_variables, f_mod, parameter)
  File "/export/donahue5/anaconda2/envs/e3sm_diags_env/lib/python2.7/site-packages/acme_diags/derivations/acme.py", line 19, in process_derived_var
    'The variable %s was not in the derived variables dictionary' % var_key)
RuntimeError: The variable PRECL was not in the derived variables dictionary
```
I went ahead and added them to the derived variables dictionary but got a different error.  Would it be possible to be able to have E3SM-diags take a non-derived variable?  Or have some instructions on how to add variables to the derived variables dictionary?

**Comment by AaronDonahue** [comment]
@zshaheen , Absolutely, thanks for putting the whole program together and getting back to me.  Sorry for the late reply, I didn't see the response in my emails.

To answer your question.  I tried to add a new `derived variable` to the dictionary in the file ` acme_diags/acme_diags/derivations/acme.py`, `line 424`.  I was trying to add a model to model diagnostic for PRECL and PRECC which are two standard E3SM outputs.  I followed the `PREH2O` entry as my guide to what info should go where since that also takes a standard E3SM output, `TMQ` without passing the value to a function or anything. 

I may have just gone about this the wrong way.  Or perhaps I didn't quite understand correctly this link: `https://e3sm-project.github.io/acme_diags/docs/html/add-new-diagnostics.html`.  I can try again, maybe I have to add it to the `params.py` file instead of directly in the code?

**Comment by zshaheen** [comment]
@AaronDonahue Just so I get what you're doing, you have two sets of plots you want:
* Compare PRECL from two models
* Compare PRECC from two models

It's not like you're trying to compare PRECL from one model, vs PRECC from another right?
Since I'm not a climatologist, I'm not even sure if people even compare two different variables from two different models.

**Comment by AaronDonahue** [comment]
@zshaheen, yes your intuition is correct, I want to compare PRECL between two models and then PRECC between two models.  So same variable different models :-)

**Comment by chengzhuzhang** [comment]
@AaronDonahue I just returned work and digging email piles.. Not sure if you and @zshaheen has solved this. Two steps are needed to add variables to model vs model:

**First,** is to add the new variable entries to an existing .cfg file. following the instruction here:
https://github.com/E3SM-Project/acme_diags/blob/master/examples/model-vs-model/model-vs-model.ipynb

For instance, adding PRECL to the default model vs model cfg, you want to copy over the default cfg from  https://github.com/E3SM-Project/acme_diags/blob/master/acme_diags/driver/default_diags/lat_lon_model_vs_model.cfg
 and add entry for PRECL in this file, following the same structure:

 ```
[#]
sets = ["lat_lon"]
case_id = "model_vs_model"
variables = ["**PRECL**"]
seasons = ["ANN", "DJF", "MAM", "JJA", "SON"]
regions = ["global"]
test_colormap = "WhiteBlueGreenYellowRed.rgb"
reference_colormap = "WhiteBlueGreenYellowRed.rgb"
diff_colormap = "BrBG"
contour_levels = [0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16]
diff_levels = [-5, -4, -3, -2, -1, -0.5, 0.5, 1, 2, 3, 4, 5]
```
**Second**, is to add the variable to the derived variable dictionary (https://github.com/E3SM-Project/acme_diags/blob/master/acme_diags/derivations/acme.py) as follows:
```
    'PRECL': OrderedDict([
        (('PRECL'), rename)
    ])
```

@zshaheen is currently working on a new method to allow the user to add variables much easier, by designing a Dataset class. We will hopefully keep  you updated on the progress very soon...

**Comment by chengzhuzhang** [comment]
It has been implemented, see documentation:https://e3sm-project.github.io/e3sm_diags/docs/html/add-new-diagnostics.html
