### ISSUE TITLE
Have a custom exception when a variable is not found using Dataset

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/e3sm_diags#174]
So instead of a `RuntimeError`, we might have a `VariableNotFoundError`. This makes it more clear what is wrong, instead of a generic error. This is for the `Dataset` class, specifically when using `Dataset.get_variable()`.

**Comment by sterlingbaldwin** [comment]
I accidentally did a run today where I pointed e3sm_diags at the wrong directory for the obs dataset, and it gave me like 100 pages of the same error. It might be worth it to do a quick sanity check at startup that the expected data files are in the location the user specifies, and give a nice "you done goofed" message.

**Comment by zshaheen** [comment]
Not needed, since the current error is already conveys this idea. Also, regardless of if a variable is missing, the error is still caught and handled correctly.
