### ISSUE TITLE
Equivalent to short_test_name for reference?

### ISSUE THREAD

**Issue by kaabre** [E3SM-Project/e3sm_diags#183]
It used to be that 'reference_name' and 'ref_name' were separate parameters and one was equivalent to short_test_name, but this is no longer apparently the case.

What is the parameter that allows me to specify what the reference should be called on the plots?  (not the title, because I want to avoid printing out the long string of the model name in the first place)

**Comment by chengzhuzhang** [comment]
Hey @kaabre , what run type do you have? I am guessing that you are doing a model vs model run and wanted to print a short reference model name? If this is the case, you can set 'reference_name' with a short name that you desire. Otherwise, please let me know your configuration and I will try to help.

**Comment by kaabre** [comment]
Using a model_vs_model run type, yes.

Actually, model_vs_model doesn't seem to work at all for me.  When I run it with the parameters (on Edison) --

```
reference_data_path = '/global/cscratch1/sd/leebrent/climos/output/20161118.beta0.F1850COSP.ne30_ne30.edison'
#reference_name = '20161118.beta0.F1850COSP.ne30_ne30.edison'
reference_name = 'someshortname'

test_data_path = '/global/cscratch1/sd/leebrent/climos/output/20161118.beta0.FC5COSP.ne30_ne30.edison'
test_name = '20161118.beta0.FC5COSP.ne30_ne30.edison'

# Not defining a sets parameter runs all of the default sets:
# ['zonal_mean_xy', 'zonal_mean_2d', 'lat_lon', 'polar', 'cosp_histogram']

run_type = 'model_vs_model'

# optional settings below
diff_title = 'Test - Ref'

backend = 'mpl'  # 'mpl' is for the matplotlib plots.

#results_dir = 'diag_demo'  # name of folder where all results will be stored

multiprocessing = True
num_workers =  24
```

(Basically the same as the all_sets demo, except with two models)

I get these errors:

AttributeError: 'ACMEParameter' object has no attribute 'ref_name'
  File "/global/homes/l/leebrent/.conda/envs/e3sm_diags_env_20181010/lib/python2.7/site-packages/acme_diags/driver/zonal_mean_xy_driver.py", line 77, in run_diag
    ref_name = parameter.ref_name
AttributeError: 'ACMEParameter' object has no attribute 'ref_name'
There was not a single valid diagnostics run, no viewer created.

I don't get these errors on a model_vs_obs run.  I'm using the most recent version of the model (non-development version).

**Comment by chengzhuzhang** [comment]
@zshaheen you are correct. 

ref_name is used to search for the file. And reference_name is the text printed on the plot.. We can probably come up with more descriptive names for these two parameters.

**Comment by kaabre** [comment]
Oh, thanks.  Ref_name wasn't in the 'available parameters' list so I forgot to include it.  Thanks!

**Comment by zshaheen** [comment]
- [ ] @zshaheen: Add `short_ref_name` parameter to documentation.

**Comment by zshaheen** [comment]
We need to better organize these related parameters. We have:
* `ref_name`
* `reference_name`
* `short_ref_name`

and for test, we have:
* `test_name`
* `short_test_name`

Why does the reference have both `ref_name` and `reference_name`?

**Comment by chengzhuzhang** [comment]
`reference_name`: Optional text to be specified by the users to be printed upper left above the ref figure.
`ref_name`: the text used to search for the according reference data file.
Documentation updated.
