### ISSUE TITLE
Extra numbers in reference_name?

### ISSUE THREAD

**Issue by kaabre** [E3SM-Project/e3sm_diags#184]
When I run the code (which includes just "V1 F2000" as the reference_name) it has this output:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/21698499/46840233-c8976480-cd76-11e8-813a-d09e1a0386cf.png">

How do I get rid of the (1-11) next to the reference_name?  What is it referring to?  (I'm assuming to the years present in the climo file, and if that is the case, why doesn't one appear for the test case?)

**Comment by chengzhuzhang** [comment]
Hi @kaabre, (1-11) is simulation years, which is read from metadata of simulation files. This helps to indicate the years averaged for climatology. We don't have a mechanism to leave out  these numbers though. And you are right, this should be done also for the reference plot for model-vs-model. I'm assigning myself to work on this.

**Comment by kaabre** [comment]
Thanks!

**Comment by chengzhuzhang** [comment]
Done
