### ISSUE TITLE
Support for Cori

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/e3sm_diags#192]
@singhbalwinder had issues running `e3sm_diags` on Cori. We plan on having a quick start guide for Cori soon, especially since Edison is retiring early next year.

Befikre ho phaijaan, hum eh cheez ko karenge.

**Comment by singhbalwinder** [comment]
Thanks for opening this issue! Please let me know if you need any help from my side.

> Befikre ho phaijaan, hum eh cheez ko karenge.
 :blush:, shukriya!

**Comment by zshaheen** [comment]
Hi @singhbalwinder, @oksanaguba,

I've created the quick guide for Cori in case you're still interested on the E3SM Diagnostics [documentation site](https://e3sm-project.github.io/acme_diags/docs/html/quickguides/quick-guide-cori.html). I tested this and it works for me. Please let us know if there are any issues and we'll fix them. Thanks again for using this 😄 .

In case you're curious, in our case, all of the files accessible via Edison are accessible via Cori. The difference is that Cori requires you to specify what type of compute node you want to run with. So any `salloc` or `srun` command requires a `-C` argument. Below is some quick information about the two types of compute nodes:

* Cori KNL:
    * 68 cores/node
    * 128 GB/node
    * Use `-C knl`.
* Cori Haswell:
    * 32 cores/node
    * 128 GB/node
    * Use `-C haswell`.

**Comment by oksanaguba** [comment]
Thanks -- I was lucky enough and used mostly Edison's login nodes for diagnostics. I will try and see if just a login node is enough for cori too.

**Comment by singhbalwinder** [comment]
Thanks a lot @zshaheen ! I will give it a try.

**Comment by zshaheen** [comment]
@oksanaguba We're using Shifter to run the container. Interestingly enough, Shifter works on the login nodes for Cori, but not for Edison. I emailed NERSC support months ago, I guess we'll see what happens.

**Comment by singhbalwinder** [comment]
This is the first time I tried running these diags so I might be doing something stupid. I get the following error when I run these on Cori:
```--2018-12-17 16:29:33--  https://raw.githubusercontent.com/E3SM-Project/acme_diags/master/acme_diags/container/e3sm_diags_container.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.200.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.200.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6938 (6.8K) [text/plain]
Saving to: 'e3sm_diags_container.py'

     0K ......                                                100% 3.48M=0.002s

2018-12-17 16:29:33 (3.48 MB/s) - 'e3sm_diags_container.py' saved [6938/6938]

Mon Dec 17 16:29:51 2018: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Mon Dec 17 16:29:51 2018: [unset]:_pmi_init:_pmi_alps_init returned -1
[Mon Dec 17 16:29:51 2018] [c3-0c0s15n0] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537):
MPID_Init(247).......: channel initialization failed
MPID_Init(636).......:  PMI2 init failed: 1
Using the command: shifter --volume=$REFERENCE_DATA_PATH:/reference_data_path --volume=$TEST_DATA_PATH:/test_data_path --volume=$RESULTS_DIR:/results_dir --image=docker:e3sm/\
e3sm_diags:latest -- e3sm_diags '-p' 'myparams.py'
```

My params files is:
```reference_data_path = '/global/cscratch1/sd/bsingh/other_machs/anvil/SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2_strt_pt/run/'
test_data_path = '/global/cscratch1/sd/bsingh/other_machs/anvil/SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2/run'

test_name = 'SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2'
ref_name = 'SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2_strt_pt'

# Not defining a sets parameter runs all of the default sets:
# ['zonal_mean_xy', 'zonal_mean_2d', 'lat_lon', 'polar', 'cosp_histogram']

# 'mpl' and 'vcs' are for matplotlib or vcs plots respectively.
backend = 'mpl'

# Name of folder where all results will be stored.
results_dir = 'diag_demo'

run_type = 'model_vs_model'

# Optional settings below:

diff_title = 'Test Model - Ref Model'

multiprocessing = True
# You can set this to 64 if running on the KNL nodes.
num_workers =  32

```

Following is my submit script:
```
#!/bin/bash -l
#SBATCH --job-name=diags
#SBATCH --output=diags.o%j
#SBATCH --account=acme
#SBATCH --nodes=1
#SBATCH --time=00:30:00
#SBATCH -C haswell
#SBATCH  -q debug


# Please change the directory below.
cd ~/amwg/acme_diags/
wget https://raw.githubusercontent.com/E3SM-Project/acme_diags/master/acme_diags/container/e3sm_diags_container.py
python e3sm_diags_container.py --shifter -p myparams.py

```

I will really appreciate any help on this. Thanks!

**Comment by chengzhuzhang** [comment]
Hello, @singhbalwinder 
I took a look at your test_data_path on Nersc. And realized that you have all the h0 files in that path. However, at this stage, e3sm_diages only read climo files as input (see [here](https://e3sm-project.github.io/acme_diags/docs/html/index.html#input-data-requirment)). Basically, you want to apply e3sm_diags on post-processed model files using NCO. Please let us know if you need help with that. 

Thanks,
Jill

**Comment by singhbalwinder** [comment]
Thanks @chengzhuzhang ! That makes sense. I will re-grid the files and try once more.

**Comment by singhbalwinder** [comment]
There seems still something missing. I have regridded files and updated `myparams.py` with the paths which has climo files. I am still getting similar error:
```
--2018-12-20 11:17:07--  https://raw.githubusercontent.com/E3SM-Project/acme_diags/master/acme_diags/container/e3sm_diags_container.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.248.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.248.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6938 (6.8K) [text/plain]
Saving to: 'e3sm_diags_container.py.1'

     0K ......                                                100% 4.22M=0.002s

2018-12-20 11:17:08 (4.22 MB/s) - 'e3sm_diags_container.py.1' saved [6938/6938]

Thu Dec 20 11:17:24 2018: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Thu Dec 20 11:17:24 2018: [unset]:_pmi_init:_pmi_alps_init returned -1
[Thu Dec 20 11:17:24 2018] [c3-0c1s10n1] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537):
MPID_Init(247).......: channel initialization failed
MPID_Init(636).......:  PMI2 init failed: 1
Using the command: shifter --volume=$REFERENCE_DATA_PATH:/reference_data_path --volume=$TEST_DATA_PATH:/test_data_path --volume=$RESULTS_DIR:/result\
s_dir --image=docker:e3sm/e3sm_diags:latest -- e3sm_diags '-p' 'myparams.py'
```

Here is my `myparams.py` file:
```
reference_data_path = '/global/cscratch1/sd/bsingh/other_machs/anvil/SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2_strt_pt/run/climo_fv/2-11yr/'
test_data_path = '/global/cscratch1/sd/bsingh/other_machs/anvil/SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2/run/climo_fv/2-11yr/'

test_name = 'SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2'
ref_name = 'SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2_strt_pt'

# Not defining a sets parameter runs all of the default sets:
# ['zonal_mean_xy', 'zonal_mean_2d', 'lat_lon', 'polar', 'cosp_histogram']

# 'mpl' and 'vcs' are for matplotlib or vcs plots respectively.
backend = 'mpl'

# Name of folder where all results will be stored.
results_dir = 'diag_demo'

run_type = 'model_vs_model'

# Optional settings below:

diff_title = 'Test Model - Ref Model'

multiprocessing = True
# You can set this to 64 if running on the KNL nodes.
num_workers =  32

```

**Comment by zshaheen** [comment]
@singhbalwinder I'm trying to run your example to see what's wrong. However, I don't have permission to both the `test_data_path` or `reference_data_path`. The permissions in the directiory of your old parameter file worked:
```
/global/cscratch1/sd/bsingh/other_machs/anvil/SMS_Ly10.ne30_ne30.FC5AV1C-L.anvil_intel.clb_v2/run
```
If you could fix this issue, I'll gladly go ahead and test to see what's wrong. Thanks!

**Comment by singhbalwinder** [comment]
I have fixed the permissions now. Thanks for looking into it!

**Comment by zshaheen** [comment]
@singhbalwinder I was able to run your example `myparams.py` and it works for me. However, I did this in **interactive mode**, I did not submit a batch job. I'm going to try submitting a batch job and we'll see how that goes.

Regardless, [here are your results in case you're curious](http://portal.nersc.gov/project/acme/shaheen2/balwinder_example_dont_delete/viewer/).

**Comment by singhbalwinder** [comment]
Great! Thanks @zshaheen !

**Comment by chengzhuzhang** [comment]
Support for Cori was done a while ago, here is [a quick start guide ](https://e3sm-project.github.io/e3sm_diags/docs/html/quickguides/quick-guide-cori.html#)
