### ISSUE TITLE
python warnings on edison

### ISSUE THREAD

**Issue by chengdang** [E3SM-Project/e3sm_diags#201]
I'm running E3SM diagnostics on NERSC Edison and I am able to produce plots. While during the run, I got numerous warnings from python, for example:

> /opt/conda/lib/python2.7/site-packages/numpy/ma/core.py:1016: RuntimeWarning: overflow encountered in multiply
>   result = self.f(da, db, *args, **kwargs)
> 
> /opt/conda/lib/python2.7/site-packages/cartopy/crs.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
> 
> /opt/conda/lib/python2.7/site-packages/numpy/ma/core.py:3169: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
>   dout = self.data[indx]

Will these warnings impact the quality of generated plots?

Thanks,

**Comment by zshaheen** [comment]
Hi @chengdang, thanks for using the software! These errors arise from using an updated version of `numpy`, while what we use for our metrics, `cdms`, hasn't refactored its code to get rid of the warnings.

We did a check of the actual metrics generated between versions and all was the same. So to answer your question, to our knowledge, these warnings **do not** affect the quality of the plots.

Please let us know if you have any other questions!

**Comment by xylar** [comment]
@zshaheen and @chengdang, this warning comes up quite often in recent conda installations.  It seems to be a cython issue interacting with numpy, see:
https://github.com/numpy/numpy/issues/11788#issuecomment-423078169

Anyway, safe to ignore and probably nothing to do with e3sm_diags or cdms.

**Comment by chengdang** [comment]
Thank you for answering my question @zshaheen @xylar
