### ISSUE TITLE
Install fails with python=3 on osx

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/e3sm_diags#207]
When trying to install e3sm_diags on mac, conda fails to solve the environment if python=3 is set. If python=3 isnt set, it downgrades the environment to py2.7.

```
>> conda create -n diags -c e3sm -c conda-forge -c cdat e3sm_diags python=3
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - e3sm_diags
  - python=3
Use "conda info <package>" to see the dependencies for each package.```

**Comment by chengzhuzhang** [comment]
Thanks @sterlingbaldwin  for reporting this. This morning I'm creating envs for a user,

conda create -n e3sm_diags_env_for_phil -c cdat/label/v81 -c conda-forge cdat matplotlib cartopy beautifulsoup4 lxml  (failed, with python 3)

conda create -n e3sm_diags_env_for_phil_py2 -c cdat/label/v81 -c conda-forge cdat matplotlib cartopy beautifulsoup4 lxml python=2 (worked)

Need further investigation there.

**Comment by sterlingbaldwin** [comment]
When I mentioned this to @zshaheen he thought it had something to do with cdp v1.4.0 which had been built for python=3 OSX.

**Comment by xylar** [comment]
@sterlingbaldwin and @zshaheen, I don't think cdp can be the problem unless a weird version is being pinned somewhere.  1.4.2 has been built no-arch so it should work on OSX and linux with any version of python:
https://anaconda.org/conda-forge/cdp/files

**Comment by xylar** [comment]
So cdp might explain why @sterlingbaldwin's command didn't work but it doesn't explain why @chengzhuzhang's test environment didn't work.

**Comment by xylar** [comment]
@chengzhuzhang, can you tell us which package(s) specifically fail in your osx test environment?

**Comment by zshaheen** [comment]
When building the Python 3 versions of `e3sm_diags` v1.5.0 and v1.6.0 on macOS, there was some missing dependency of a dependency not available. I didn't investigate this further, since no one really uses the Python 3 version, especially on macOS.

I'll actually investigate this now, as we should be slowly transitioning to Python 3 anyways.

One note is that an older version of `e3sm_diags`, v1.4.0, did have a Python 3 build on macOS. But that's no longer working, since the old builds of `cdp` were removed 👎

**Comment by zshaheen** [comment]
So here's how to proceed:
* Update the versions of the stuff from cdat to the latest versions, as they work on macOS with Python 3.
* Release another `e3sm_diags`.

This isn't too bad.

**Comment by xylar** [comment]
> But that's no longer working, since the old builds of cdp were removed ￼

Yeah, that was pretty terrible...

**Comment by chengzhuzhang** [comment]
Thanks @xylar. Just talked to Zeshawn, in my case, the installation works, but the e3sm_diags system tests failed with python 3. I am filing a separate issue on this.

**Comment by xylar** [comment]
@zshaheen 
>  Update the versions of the stuff from cdat to the latest versions, as they work on macOS with Python 3.
> Release another `e3sm_diags`.

If you want a new release, you can do that.  But if all you're changing is the conda recipe, you should just change the build number from 0 to 1 (I think your conda recipe is missing the build number so it defaults to 0).  It's better to consider the conda recipe as separate from the rest of the code (in fact, it usually makes sense to have it completely separate from the code, like on conda-forge).  This way, the procedure is to release a version of the code and only then to update the conda recipe to work with the new release.  Maybe you know all this already but I figured I'd check.

**Comment by zshaheen** [comment]
For *now*, the below command works, on macOS and Linux:
```
conda create -n e3sm_diags_v1.7.0_py3 e3sm_diags python=3 -c e3sm -c conda-forge -c cdat
```

Note that we don't really officially support macOS via the other installation method (installing from the yml). However, we do have a [quick guide with Docker](https://e3sm-project.github.io/e3sm_diags/docs/html/quickguides/quick-guide-docker.html) that a user on macOS can use. I've used this many times.
