### ISSUE TITLE
How to generate climo files from e3sm diagnostics.

### ISSUE THREAD

**Issue by itsanikesh** [E3SM-Project/e3sm_diags#210]
Hi,
Can someone guide me how to generate climo files from h0 files using e3sm-diagnostics?
Thanks
Anikesh

**Comment by zshaheen** [comment]
Hi @itsanikesh, as per your other issue, use the link below to generate the climo files: https://e3sm-project.github.io/e3sm_diags/docs/html/input-data-requirement.html

For a sample directory of how the model files should look like, see the below directories:
* NERSC: `/global/project/projectdirs/acme/acme_diags/test_model_data_for_acme_diags/climatology/`
* ALCF: `/lus/theta-fs0/projects/ClimateEnergy_3/e3sm_diags/test_model_data_for_e3sm_diags/climatology/`

If you have any issues or need help, let us know!

**Comment by zshaheen** [comment]
Let us know if you have issues. Otherwise, I'm closing this issue.
