### ISSUE TITLE
MPI failure in batch mode on Edison/Cori?

### ISSUE THREAD

**Issue by kaabre** [E3SM-Project/e3sm_diags#212]
When ran in batch mode, diagnostic runs fail while initiating MPI and do not produce output.  @beharrop ran into this problem on Edison but I've also reproduced it on Cori, under both the latest shifter image and the v1.5.0 image.  The demo also fails this way (lat_lon and all_sets demo).  However, when run on an interactive node with the exact same commands and parameters, it does not fail (at least in the latest version).  

Fri Mar 29 13:38:54 2019: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Fri Mar 29 13:38:54 2019: [unset]:_pmi_init:_pmi_alps_init returned -1
[Fri Mar 29 13:38:54 2019] [c5-0c0s14n3] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537):
MPID_Init(247).......: channel initialization failed
MPID_Init(636).......:  PMI2 init failed: 1

**Comment by zshaheen** [comment]
Hi @kaabre, I'll try to reproduce this error. Is this the full output? If not, can you post it? Thanks!

**Comment by chengzhuzhang** [comment]
Hello @kaabre, do you still have this issue?

**Comment by zshaheen** [comment]
Others, like Chris and Qi are having this issue. I'm going to look at this.

**Comment by zshaheen** [comment]
I'm also getting issues just running the container, please see below. I'm in contact with NERSC support.

```
$ shifter --volume=/global/u2/z/zshaheen/github/acme_diags/tests/system:/reference_data_path --volume=/global/u2/z/zshaheen/github/acme_diags/tests/system:/test_data_path --volume=/global/u2/z/zshaheen/github/acme_diags/tests/system/all_sets_results:/results_dir --image=docker:e3sm/e3sm_diags:latest -- e3sm_diags                                       
ERROR: unclean exit from bind-mount routine. /var/udiMount/reference_data_path may still be mounted.
BIND MOUNT FAILED from /var/udiMount//global/u2/z/zshaheen/github/acme_diags/tests/system to /var/udiMount/reference_data_path
FAILED to setup user-requested mounts.
FAILED to setup image.
```

**Comment by tangq** [comment]
@zshaheen , good to know that you can reproduce the errors. I will be interested in knowing the solutions.

**Comment by zshaheen** [comment]
Some good news. @dnadeau4 stated that running in the interactive mode works.
