### ISSUE TITLE
Support Python 3 as the default environment

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/e3sm_diags#215]
Currently, we technically support both Python 2 and 3, but the Python 3 version of the code breaks. To make life easier, we're just going to support Python 3. 

When doing this, we need to regenerate all of the observational data in a Python 3 environment. So @chengzhuzhang, make sure you have `python=3` in your `conda create` command for the environment.

**Comment by xylar** [comment]
Could you explain why the observational data changes with python environment and why it needs to be regenerated?  That sounds surprising to me.

**Comment by chengzhuzhang** [comment]
The scripts for processing analysis data are still python 2. However it won't affect running e3sm_diags package itself.

**Comment by chengzhuzhang** [comment]
the environment to generate obs data is a separate problem. We are still figuring out why the python 3 version of e3sm_diags breaks.

**Comment by zshaheen** [comment]
> Could you explain why the observational data changes with python environment and why it needs to be regenerated? That sounds surprising to me.

I'm not sure that it would. I'm really hoping there's no difference between the obs when generated in a Python 2 vs Python 3 env, but it doesn't hurt to check.

**Comment by zshaheen** [comment]
This was done in the [v1.7.0](https://github.com/E3SM-Project/e3sm_diags/releases/tag/v1.7.0) version of `e3sm_diags` and henceforth, all version of `e3sm_diags` will only support Python 3. Most users will **not** have any changes with how they install or use the software.
