### ISSUE TITLE
unable to create an anaconda (developer) environment following the documentation

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#224]
@oksanaguba and I have both see the same types of errors (though for slightly different packages) trying to install the development environment, following the docs.  Here's what I see:
```
...
$ conda env create -f e3sm_diags_env_dev.yml
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gst-plugins-base=1.14.4
  - pyqt=5.9.2
  - sqlite=3.26.0
Use "conda search <package> --info" to see the dependencies for each package.
```

And here is what @oksanaguba sees:
```
$ conda env create -f e3sm_diags_env.yml
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - glib=2.58.3
  - pyqt=5.9.2
  - sqlite=3.26.0
Use "conda search <package> --info" to see the dependencies for each package.
```

More detail here:
https://github.com/E3SM-Project/e3sm_diags/issues/182#issuecomment-499211134

**Comment by xylar** [comment]
Ah, I see that @oksanaguba is installing the non-developer version, whereas I was installing the developer environment.  That may account for the different packages that give us errors, and suggests that both yamls aren't working :-(

**Comment by oksanaguba** [comment]
Thanks @xylar !

**Comment by xylar** [comment]
@oksanaguba, I'm trying to work on a workaround for you in the meantime.  I'll post here soon...

**Comment by xylar** [comment]
@oksanaguba, please try running:
```
conda create -n e3sm_diags_env_dev python=3.7 cdp=1.4.2 vcs=8.1 vtk-cdat=8.2.0rc2.8.1 \
    vcsaddons=8.1 dv3d=8.1 cdms2=3.1.2 cdutil=8.1 genutil=8.1.1 cdtime=3.1.2 numpy matplotlib \ 
    cartopy beautifulsoup4 lxml flake8 -c conda-forge -c cdat -c cdat/label/v81

source activate e3sm_diags_env_dev
```
This worked for me.  Then, continue following the [Environment for development](https://e3sm-project.github.io/e3sm_diags/docs/html/install.html#environment-for-development) instructions (the second section, not the first called "Latest stable release") at step 5:
```
git clone https://github.com/E3SM-Project/e3sm_diags.git
```

**Comment by chengzhuzhang** [comment]
@xylar Thank you so much for helping out. We still need to figure out why the yml broke and work on stabilize it.

**Comment by xylar** [comment]
@chengzhuzhang, unfortunately yaml files aren't a very good way to preserve an environment.  There is a lengthy and not very productive discussion here:
https://github.com/conda-forge/conda-forge.github.io/issues/787

The suggestions in the end are to use a container (as you are) or to use conda-pack to tar up the environment and store it somewhere.  There's no sign that yaml files will be stable over longer periods of time (even days to weeks is all they last sometimes) anytime in the near future :-(

**Comment by chengzhuzhang** [comment]
The yaml installation just worked last weekend and it is broken today. Glad we went with containers. I guess we should leave a note in the documentation to disclose the risk of using yml and suggest alternative methods. 

There is a side note, we will release 1.7.1 with the new parameter. Will update the unified-env confluence page after the release. 

I forgot to mention, your work around just worked. Thank you!

**Comment by oksanaguba** [comment]
I still have an issue. Do I need 
```
source activate e3sm_diags_env
```
or not? With it I get this error:
```
(e3sm_diags_env) [onguba@blueslogin2 climoout.17070-0002-0006]$ e3sm_diags -p myparams-vs-default-zonal.py
-bash: e3sm_diags: command not found
(e3sm_diags_env) [onguba@blueslogin2 climoout.17070-0002-0006]$ e3sm_diags_env -p myparams-vs-default-zonal.py
-bash: e3sm_diags_env: command not found
```
and without it the error is different:
```
(base) [onguba@blueslogin2 climoout.17070-0002-0006]$ e3sm_diags -p myparams-vs-default-zonal.py
Traceback (most recent call last):
  File "/home/onguba/miniconda3/bin/e3sm_diags", line 6, in <module>
    from acme_diags.acme_diags_driver import main
  File "/home/onguba/miniconda3/lib/python3.7/site-packages/acme_diags/acme_diags_driver.py", line 21, in <module>
    import cdp.cdp_run
ModuleNotFoundError: No module named 'cdp'
```
Thanks!

**Comment by chengzhuzhang** [comment]
@oksanaguba Yes source activate is needed. According to Xylar's command, it should be:
```
source activate e3sm_diags_env_dev
```
Because this is development env, installation is needed after git clone the master, do following to clone and install:
```
git clone https://github.com/E3SM-Project/e3sm_diags.git
pip install .
```
After installation, please try run the system test to see, if everything is okay
```
cd tests/system
e3sm_diags -d all_sets.cfg
```
These steps work on my end.. let me know if this works...

**Comment by oksanaguba** [comment]
Thanks @xylar @chengzhuzhang , my issue was that i ran pip install before activating environment. All works now, and new pressure levels, too.

**Comment by chengzhuzhang** [comment]
Glad to know it is working now! Thank you for the update :)

**Comment by zshaheen** [comment]
We'll close this issue when the yamls for the Anaconda environment work.

**Comment by chengzhuzhang** [comment]
The yamls for v2 have been tested and work.
