### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/e3sm_diags#232]
We need to add more unit tests to the software. There are some in the [`test`](https://github.com/E3SM-Project/e3sm_diags/tree/master/tests) directory. Specifically, we need to add tests for the `Dataset` class. Please see #190 regarding this.

**Comment by zshaheen** [comment]
There's also a [`create_test_data.py`](https://github.com/E3SM-Project/e3sm_diags/blob/master/tests/testing_data/create_test_data.py) script that downloads some test data and creates a smaller data sets. The total is about 400mb.

After that data is created, another script should be added that actually downloads the data from `/lcrc/group/acme/public_html/e3sm_diags_test_data` on `blues.lcrc.anl.gov`. This 400mb of data that was created with `create_test_data.py` should be put there and served from there. We shouldn't have this much testing data in the directory.

**Comment by chengzhuzhang** [comment]
will keep #190 
Tests data are now moved to lcrc and a download script is implemented to download files.https://github.com/E3SM-Project/e3sm_diags/pull/372
