### ISSUE TITLE
Have a script that converts old parameter files to use the new way

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/e3sm_diags#239]
When making changes to the parameters used in certain plotsets (as proposed in [this comment by @chengzhuzhang](https://github.com/E3SM-Project/e3sm_diags/issues/238#issue-470022876)), there might be some issues that will break when running the diagnostics "the old way". The old way is this:
```
e3sm_diags -p something.py
```

I propose that there be a script, called `convert_to_new_way.py` or something, that will convert this old `something.py` to [run the diagnostics using the API](https://e3sm-project.github.io/e3sm_diags/docs/html/examples/run-e3sm-diags-api.html). A user will just `wget`/`curl` this script and run the following:

```
$ convert_to_new_way.py something.py
Your parameter file, something.py, has been converted to something-converted.py.
To run your diags in an environment with e3sm_diags installed, please run it like so:
   python something-converted.py
```

---

Writing a script that does this shouldn't be too bad. Given a parameter file [like this below](https://e3sm-project.github.io/e3sm_diags/docs/html/quickguides/quick-guide-cori.html#cori-params):
```py
reference_data_path = '/global/project/projectdirs/acme/acme_diags/obs_for_e3sm_diags/climatology/'
test_data_path = '/global/project/projectdirs/acme/acme_diags/test_model_data_for_acme_diags/climatology/'

test_name = '20161118.beta0.FC5COSP.ne30_ne30.edison'

sets = ['lat_lon']
seasons = ['ANN']

# Name of folder where all results will be stored.
results_dir = '/global/project/projectdirs/acme/www/shaheen2/runs_with_api/lat_lon_demo'
```

we'd need to convert it to something [like this](https://e3sm-project.github.io/e3sm_diags/docs/html/examples/run-e3sm-diags-api.html#running-from-the-cori-quick-start-guide):

```py
import os
from acme_diags.parameter.core_parameter import CoreParameter
from acme_diags.run import runner

param = CoreParameter()

param.reference_data_path = '/global/project/projectdirs/acme/acme_diags/obs_for_e3sm_diags/climatology/'
param.test_data_path = '/global/project/projectdirs/acme/acme_diags/test_model_data_for_acme_diags/climatology/'
param.test_name = '20161118.beta0.FC5COSP.ne30_ne30.edison'
param.seasons = ["ANN"]

prefix = '/global/project/projectdirs/acme/www/shaheen2/runs_with_api'
param.results_dir = os.path.join(prefix, 'lat_lon_demo')

runner.sets_to_run = ['lat_lon']
runner.run_diags([param])
```

Basically everything that doesn't start with `param.<some_parameter>` is boilerplate code. You'd go thorough the original `something.py` and:
* Add any `import` statements with the other `import` statements in `something-converted.py`.
* Any parameter, like `reference_data_path = '...'`, should be converted to `param.reference_data_path = '...'`.
  * **This can cause an issue, if the user has something originally like this:**
    ```py
    prefix = '/global/project/projectdirs/acme/www/shaheen2/runs_with_api'
    results_dir = os.path.join(prefix, 'lat_lon_demo')
    ```
    Converting this would result in:
    ```py
    param.prefix =  '/global/project/projectdirs/acme/www/shaheen2/runs_with_api'
    # The below won't work, since the `prefix` variable isn't defined, it's `param.prefix`.
    param.results_dir = os.path.join(prefix, 'lat_lon_demo')
    ```
    This is probably not common however.
* Since `sets` are inputted via `runner.sets_to_run = ['you', 'sets']` and not `param.sets`, you'll need a special case to handle this.

**Comment by zshaheen** [comment]
Another way is to do this internally. Like when you run:
```
e3sm_diags -p something.py
```

the main driver can detect this and automatically create a `CoreParameter` object. Then it can pass it in into `acme_diags.run.runner`. So no there's no preprocessing step needed to be done by the users. 

To do so, you'd do all of the logic explained in my first comment under [this if-clause](https://github.com/E3SM-Project/e3sm_diags/blob/7418a914c445f7d5cb287534861cb3e1fc579b4e/acme_diags/acme_diags_driver.py#L285).

The point of doing this is to **have the same code to run the diags with the "old way" and the newer way**.

**Comment by zshaheen** [comment]
1. Is this even needed? I think it would make it so there's less testing required. Cause as of now, you'd need to make sure that backwards compatibility is still supported (`e3sm_diags -p something.py`). If you do my second idea, the code internally would be mostly the same. Most of the "old way" code is under [`get_parameters()`](https://github.com/E3SM-Project/e3sm_diags/blob/7418a914c445f7d5cb287534861cb3e1fc579b4e/acme_diags/acme_diags_driver.py#L285).
2. If this is a good idea, should there be an auxiliary script (first comment), or should `e3sm_diags` internally do this (second comment).

@chengzhuzhang and @golaz, what are your thoughts?

**Comment by chengzhuzhang** [comment]
@zshaheen  Wow, It a pleasant supersize to see your updates here! Thank you for your input on this. Our original plan was that, when releasing v2.0.0, the old diags will be still ran using the old way. While for the new diags, the users need to use the API way to run. Eventually, we want the users to phase in to use the new way. The solution you proposed can help to keep the user habits without changing.

I spent sometime during the weekend to think about this transition with the issue https://github.com/E3SM-Project/e3sm_diags/issues/238 in mind, but in another aspect: the core parameters we had before are for the previous 5-6 diags sets and they are not set-specific. With the new sets, only a couple of them are useful. The cleanest way is to do a complete 'set-specifying', i.e., each existing diags should have its own parameter and parser files. This is cleanest, but will end up with a longer parameter python script to run and need additional scripts for backward comparability. Another way is like the solution Zeshawn provided in https://github.com/E3SM-Project/e3sm_diags/issues/238. This works, but when including more diags, similar cases need to be taken care of. 

I'm working on the area-mean-time-series set, which is a set mostly independent of the other diags sets. I'm having a thought that it is perhaps not needed to have all sets configured for one run. We can have multiple configuration files for multiple sets. [one set of configuration files for the current 5-6 sets, and more for other sets]. When we consider evaluating output from other components or from higher time frequency datasets. It is perhaps inevitable to do so.  I'm experimenting different options and will provide some prototypes to discuss with @golaz later.

**Comment by zshaheen** [comment]
Sounds good @chengzhuzhang!

**Comment by chengzhuzhang** [comment]
We will do this if requested. close for now.
