### ISSUE TITLE
use cdutil.generateLandSeaMask() to generate land/sea mask ad hoc

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#240]
In today's cdat tutorial given by @doutriaux1 , I learned that cdutil has a built in function to generate land/sea masks, which is based  on  a  high-resolution  (1/6-degree  longitude/latitude)  data  set  that provides  the  fraction  land  in  each  grid  cell. documentation see [here](https://pcmdi.llnl.gov/report/pdf/58.pdf?id=39)

example of use:
```
import MV2
msk = MV2.greater(cdutil.generateLandSeaMask(std_obs), .5)
std_obs = MV2.masked_where(msk, std_obs)
```
Our current logic to generate masks is as following:
Before all the calculation starts, the drivers look for variables for generating masks: When 'LANDFRAC' and 'OCNFRAC' exist in the file, we use these two variables to apply mask.
Otherwise we use the climo 'LANDFRAC' and 'OCNFRAC' of a ne30 file saved in the package. Using the new way we can simplify the codes and apply masks as needed.

**Comment by zshaheen** [comment]
Just curious @chengzhuzhang, would there ever be a reason where someone would want the land and sea mask in the data over the ‘cdutil’ created mask?

**Comment by chengzhuzhang** [comment]
Good question. I would think using the cdutil created mask is more advanced than our current solution, especially when no 'LANDFRAC' and 'OCNFRAC' exist. The base data set is in higher resolution (1/6 degree), which will result masked data in higher res, when apply to high res model data. In addition, the implementation will be cleaner, we don't need to include the mask data in each drivers. The masks only being calculated when they are needed. I'm implementing it right now. Hopefully, there won't be performance issue with the new way...Again, nice to see your post! Hope everything is well!

**Comment by chengzhuzhang** [comment]
An example figure with `cdutil` tool: Some major lake and river systems are masked out in these maps.
![CRU-TREFHT-ANN-land_60S90N_new](https://user-images.githubusercontent.com/13056557/61846203-10e1c800-ae5b-11e9-898d-fd0f92824b92.png)
An example figure with current method: 
![CRU-TREFHT-ANN-land_60S90N_old](https://user-images.githubusercontent.com/13056557/61846214-1f2fe400-ae5b-11e9-88f7-cd6c0698a369.png)

**Comment by doutriaux1** [comment]
@zshaheen @chengzhuzhang usually people prefer to use the actual model land sea mask, because even if it is less *correct* it is whatever the model actually ***sees*** as land/sea and it affects the result produced at these cells (different part of the code).

**Comment by chengzhuzhang** [comment]
@doutriaux1 Thanks for thanks for chiming in! In the case of comparing different models (ex. CMIP multi-model comparison), then it is good to use cdutil mask generation? cause I understand each model can be a bit different for the land sea mask?

**Comment by zshaheen** [comment]
So it seems that using the `cdutil.generateLandSeaMask()` will only replace getting the data from the `acme_ne30_ocean_land_mask.nc` file, which is totally fine. From what both of you said, users still might want to use the masking from the test data. 

If this **was not** the case and masking data was no longer needed, the `Dataset` class could be simplified. The whole concept of "extra variables" was created to account for getting `LANDFRAC` and `OCNFRAC`.

**Comment by chengzhuzhang** [comment]
According to @doutriaux1 and @dnadeau, using e3sm masks are more accurate for evaluating e3sm model data. I guess we will just keep it the old way. I might be helpful to replace the current ne30 resolution mask with a high res one for high res simulation. 

But "extra variables" are not only for `LANDFRAC` AND `OCNFRAC` but also those auxiliary variables for vertical interpolation `hyam` `hybm` `PS`....

**Comment by zshaheen** [comment]
> According to @doutriaux1 and @dnadeau, using e3sm masks are more accurate for evaluating e3sm model data. I guess we will just keep it the old way. It might be helpful to replace the current ne30 resolution mask with a high res one for high res simulation.
> 
> But "extra variables" are not only for `LANDFRAC` AND `OCNFRAC` but also those auxiliary variables for vertical interpolation `hyam` `hybm` `PS`....

Ahh yes, forgot about that! 😄

**Comment by chengzhuzhang** [comment]
I'm closing this issue. We won't implement the new way for now. Will review this option when there is need. Thanks everyone for discussion!
