### ISSUE TITLE
Refine e3sm_diags testing

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#267]
Running `python test_all_sets.py` from `e3sm_diags/tests` fails both of the tests it executes. From `e3sm_diags/tests/system`, you can run `python all_sets.py -d all_sets.cfg` or `e3sm_diags -d all_sets.cfg`, but both of these commands just produce the plots to look at, with no automated tests executed.

We may also want to add Selenium web testing to make sure the viewer's GUI is performing correctly. For instance, we could check that the NetCDF files are available for download and that the plot is being sourced from the correct png file.

**Comment by chengzhuzhang** [comment]
This is very well needed. All the tests under e3sm_diags/tests were originally planned for Jenkins testing, but were not updated since.

**Comment by chengzhuzhang** [comment]
Another well-needed enhancement for testing; a fun set of run generating hundreds of plots and we need a automated testing to know if results (metrics and figures) not changed.
