### ISSUE TITLE
Errors related to installing e3sm_diags_env_dev on compy 

### ISSUE THREAD

**Issue by xuezhengllnl** [E3SM-Project/e3sm_diags#282]
I ran into errors when I was installing e3sm_diags_env_dev on compy. 

I followed the online instruction: https://e3sm-project.github.io/e3sm_diags/docs/html/install.html#environment-for-development
After "conda env create -f e3sm_diags_env_dev.yml
          source activate e3sm_diags_env_dev"
I typed “pip install .” 
The error shows up:
ERROR: Could not install packages due to an EnvironmentError: [('/compyfs/zhen797/E3SM_post/e3sm_diags/.git/objects/pack/pack-b6effe0b13a3525932670539823797b24465d026.idx', '/tmp/pip-req-build-338kqg6x/.git/objects/pack/pack-b6effe0b13a3525932670539823797b24465d026.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-338kqg6x/.git/objects/pack/pack-b6effe0b13a3525932670539823797b24465d026.idx'"), ('/compyfs/zhen797/E3SM_post/e3sm_diags/.git/objects/pack/pack-b6effe0b13a3525932670539823797b24465d026.pack', '/tmp/pip-req-build-338kqg6x/.git/objects/pack/pack-b6effe0b13a3525932670539823797b24465d026.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-338kqg6x/.git/objects/pack/pack-b6effe0b13a3525932670539823797b24465d026.pack'")]

**Comment by forsyth2** [comment]
@xuezhengllnl Try adding `--user`. I don't think that's a perfect solution but could be a work-around in the meantime while we look into this.

**Comment by golaz** [comment]
@xuezhengllnl : I was able to successfully create a new conda development environment and install the latest version of e3sm_diags on compy. Here is what I did

```
module load anaconda3/2019.03
source /share/apps/anaconda3/2019.03/etc/profile.d/conda.sh
wget https://raw.githubusercontent.com/E3SM-Project/e3sm_diags/master/conda/e3sm_diags_env_dev.yml
conda env create -f e3sm_diags_env_dev.yml -n e3sm_diags_test
conda activate e3sm_diags_test
cd tmp
git clone https://github.com/E3SM-Project/e3sm_diags.git
cd e3sm_diags
pip install .
Processing /qfs/people/gola749/tmp/e3sm_diags
Building wheels for collected packages: e3sm-diags
  Building wheel for e3sm-diags (setup.py) ... done
  Created wheel for e3sm-diags: filename=e3sm_diags-2.0.0-cp37-none-any.whl size=488984 sha256=a4ff747d54ee1ae5fc6e75aa4a13b636169d7ebe1041d74a28010d3bce671727
  Stored in directory: /tmp/pip-ephem-wheel-cache-28o_umen/wheels/bc/f1/3d/fc31f41ac73d6416200b02712fb53cab3cd081573ee4c46fc6
Successfully built e3sm-diags
Installing collected packages: e3sm-diags
Successfully installed e3sm-diags-2.0.0

```

Note that I used `conda activate` instead of `source activate`. My understanding is that `source activate` was used for older versions of conda.

Can you try again following the same steps as I did? If it works, we should update the documentation.

**Comment by golaz** [comment]
For cori, the steps are identical except for the first two lines:

```
module load python/3.7-anaconda-2019.10
source /global/common/cori_cle7/software/python/3.7-anaconda-2019.10/etc/profile.d/conda.sh
```

**Comment by xuezhengllnl** [comment]
Thank you for the detailed instruction. I successfully installed e3sm_diags_env_dev by following the steps. 
If I don't use `conda activate`, `--user` also worked.
