### ISSUE TITLE
Bad file descriptor when using VPN

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#288]
Running `e3sm_diags` on a Mac on VPN causes the following error:
```
Fatal error in MPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(572)..............: 
MPID_Init(224).....................: channel initialization failed
MPIDI_CH3_Init(105)................: 
MPID_nem_init(324).................: 
MPID_nem_tcp_init(178).............: 
MPID_nem_tcp_get_business_card(425): 
MPID_nem_tcp_init(384).............: gethostbyname failed, ml-9624328 (errno 1)
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=3191567
:
system msg for write_line failure : Bad file descriptor
```
This issue is actually due to an error in CDMS (see https://github.com/CDAT/cdms/issues/391) but as it affects `e3sm_diags`, we are creating a link to that issue here. See #287 for more discussion.

**Comment by forsyth2** [comment]
See discussion in https://github.com/CDAT/cdms/issues/391. Running `export MPICH_INTERFACE_HOSTNAME=localhost` will allow you to run `e3sm_diags` while on VPN.

**Comment by chengzhuzhang** [comment]
This problem appears to be resolved with esmf updates.
