### ISSUE TITLE
Remove test data from repo?

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#303]
the size of test data under `test/system/` gets bigger. And we still have the issue that the repo size is too big. https://github.com/E3SM-Project/e3sm_diags/issues/204. We can place the data for system test somewhere i.e., Argon e3sm data server and delete from our repo?

**Comment by rljacob** [comment]
Yes please do not put netcdf or binary data in the github repo.

**Comment by xylar** [comment]
@chengzhuzhang, I think we had discussed this earlier but I can't find the commit right away.  It will be necessary to not just remove the data but also remove it from the commit history to reduce the size of the repo.  This will be a big headache but having a repo that's several GB is also a real heacache.

**Comment by chengzhuzhang** [comment]
@xylar, I had two attempts to resolve this issue. But haven't been able to muster up my courage to mess with the commit history :(. I will work with @forsyth2 on tackling this.

**Comment by forsyth2** [comment]
https://help.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history -> https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository. Looks like we can use the BFG Repo-Cleaner (https://rtyley.github.io/bfg-repo-cleaner/). It does look to be an involved process though. 

Might want to make a clone of the repo (all branches) in a separate directory before force pushing these changes. That way we don't permanently mess something up if something goes wrong.

**Comment by forsyth2** [comment]
I created #306 to remove the `nc` files from the entire git history. I'm keeping this issue to remove them from the current state. This issue (303) should be addressed first to make sure everything works without the `nc` files in the repo, before we try removing any reference to them in the git history.
