### ISSUE TITLE
Remove nc files from repo history

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#306]
#303 is to remove `nc` files from the repo's current state. Once that is done and all tests still run (by setting their data paths elsewhere), we can attempt to remove `nc` files from the entire git history.

**Comment by tomvothecoder** [comment]
Here are some resources for removing files from Git History:
- https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

- https://rtyley.github.io/bfg-repo-cleaner/
> The BFG is a simpler, faster alternative to git-filter-branch for cleansing bad data out of your Git repository history:
> Removing Crazy Big Files
> Removing Passwords, Credentials & other Private data

**Comment by forsyth2** [comment]
@tomvothecoder #204, #303 might have some relevant notes too.

**Comment by xylar** [comment]
Just a quick note to say that this is still causing me really big problems on Cori, where I only have 40 GB total of space in my home directory.

**Comment by tomvothecoder** [comment]
Hey @xylar, to avoid disruption in the current development efforts, this will be done after the `v2.5.0` release and before `v2.6.0` dev.

The process for getting this done is here: https://github.com/tomvothecoder/purge-repo-files
The size of the repo should reduce from ~1.75GB to < ~100MB.

**Comment by xylar** [comment]
Great, I think that's a very good plan.  I just wanted to make sure it was a priority since it's been an issue for a long time.

**Comment by tomvothecoder** [comment]
@chengzhuzhang @forsyth2 @xylar I will be working on this today.

I will let you know when it is complete. `master` will be rewritten with new SHAs so branches and forks need to be updated accordingly. More info here: https://github.com/tomvothecoder/purge-repo-files#collaborator-actions

**Comment by chengzhuzhang** [comment]
Thank you for the heads up.

**Comment by tomvothecoder** [comment]
Alrighty, this is done and the repo is now significantly smaller when cloning fresh.

You will see that `E3SM-Project/e3sm_diag/master` (`origin` if branching, `upstream` if forking) is 1480 commits ahead. You should follow the steps below to get things updated.

If you are forking:
1. Fetch latest remote `master`
2. (OPTIONAL) Keep your fork's `master` synced with upstream `master` 
   a. Delete local `master`
   b. Checkout latest `upstream/master` locally
   c. Force push

If you have an active branch based on the old `master` (forking or branching):
1. Make sure all changes have been committed
2. Squash the commits on your branch
   - Recommended so there is a single SHA to make your life easier when cherry-picking
2. Create a new branch from the latest `master`
3. Cherry-pick the SHA of your squashed commit to place your changes on top of latest `master`
   - `git cherry-pick <SHA>`
   - [More info](https://dev.to/grepliz/how-to-cherry-pick-commits-into-a-new-branch-284n) on how to cherry-pick

**Comment by xylar** [comment]
Oh, wow!  That makes such a difference!  I just did a fresh clone and it took about 5 seconds.

**Comment by forsyth2** [comment]
@tomvothecoder  Can this be closed now?

**Comment by tomvothecoder** [comment]
@forsyth2 Closed, thanks

**Comment by chengzhuzhang** [comment]
Hey @tomvothecoder I'm following your instructions to update my local repo:

    -Fetch latest origin/master
    -Delete local master
    -Checkout latest origin/master

I did `git fetch`, but not sure how to delete local master?

**Comment by forsyth2** [comment]
@chengzhuzhang 

```
git fetch origin
git checkout <any other branch besides master>
git branch -D master
git checkout -b master origin/master
```

**Comment by chengzhuzhang** [comment]
It worked. Thank you @forsyth2 !
