### ISSUE TITLE
Freeze_support() error when using multiprocessing

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#316]
It is reported by @oksanaguba that when using multiprocessing with v.2.1.0. There were multiple freeze_support() errors. I'm able to reproduce this issue with standalone e3sm_diags env and 

```
    self._launch(process_obj)
    self._launch(process_obj)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    self._launch(process_obj)
    self._launch(process_obj)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    prep_data = spawn.get_preparation_data(process_obj._name)
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    _check_not_importing_main()
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    _check_not_importing_main()
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    _check_not_importing_main()
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.3.1/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')

      
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by chengzhuzhang** [comment]
Found this related dask issue https://github.com/dask/distributed/issues/2520. A fix seems needed from cdp where dask was called. @zshaheen Any suggestions on this issue?

**Comment by xylar** [comment]
@chengzhuzhang and @zshaheen, if you have a sense of whether this is a quick fix or something bigger, that would be helpful for me.  I have rolled out E3SM-Unified with 2.1.0 on 3 machines but am holding off until I hear whether I should wait for this fix before installing on the remaining 4 or 5.

**Comment by chengzhuzhang** [comment]
@xylar  Multiprocessing was implemented through a dependency CDP by zeshawn, so I'm not confident it will be a quick one. I'm trying to fix right now. Will keep you updated.

**Comment by chengzhuzhang** [comment]
@xylar, it looks like our implementation of dask multiprocessing was not compatible with latest dask version. It possibility for is to pin down dask=2.6 (an old version, the latest is 2.20). I know it is not ideal, but could work as a quick workaround.

**Comment by xylar** [comment]
Oh, wow, that's one heck of a rollback.  I'll see what I can do but I would be pretty surprised if this doesn't cause problems for other code that uses dask.

**Comment by chengzhuzhang** [comment]
I actually tried that Dask version is compatible up to 2.15. So perhas add dask <=2.15 will give more flexibility.

**Comment by xylar** [comment]
Okay, 2.15 might be possible.  I'll see. 2.6.0 definitely didn't work.

**Comment by xylar** [comment]
distributed=2.21.0 is still getting installed.  Is that okay or do you need that pinned and rolled back, too?

**Comment by chengzhuzhang** [comment]
I think it is okay to leave it.

**Comment by xylar** [comment]
My MPAS-Analysis tests passed just fine with dask=2.15.0 so I think we can switch to that one.  Other software I'm aware of that uses dask (related to creating MPAS meshes and initial conditions) is also likely to be fine if MPAS-Analysis is, and we can always make special environments for that software anyway.  I will update the pin.  Glad we can fix this before the full rollout.

**Comment by xylar** [comment]
I would still suggest fixing this before the next E3SM-Unified so we can hopefully use the latest dask at that point.

**Comment by xylar** [comment]
@chengzhuzhang and @oksanaguba, I have updated E3SM-Unified on Anvil and Compy to use dask 2.15.0.  Could you please re-test E3SM_Diags with this change and let me know how it goes?

**Comment by zshaheen** [comment]
So if you look at [the CDP code that does the multiprocessed running](https://github.com/CDAT/cdp/blob/master/cdp/cdp_run.py), and compare that [the `e3sm_diags` code that calls it](https://github.com/E3SM-Project/e3sm_diags/blob/56d1451d8886872f693f3388bceacfdf5c1be60a/acme_diags/acme_diags_driver.py#L310-L315), you see that as per https://github.com/dask/distributed/issues/2520, this error "should" only appear when users run `e3sm_diags` with the `distributed` argument. I don't think that's the case, since running it distributedly required following [these steps in this outdated documentation on this repo's wiki](https://github.com/E3SM-Project/e3sm_diags/wiki/Running-diagnostics-distributedly).

I would hope that @oksanaguba and @chengzhuzhang didn't accidentally use the `distributed` arguement.

If that arg wasn't used but this error still appears, then I'm not really sure what's up. If you've noticed, since users only run `e3sm_diags` either in serial or on a single machine/node with multiprocessing, **I don't think `dask` is even needed.** It was only selected since we thought we'd run stuff distributedly.

So if this is a big issue and stuff still breaks, I recommend simply updating that `cdp_run` library to remove `dask` and use Python's `multiprocessing.Pool`. It's not too bad to use, [as you see in this example](https://stackoverflow.com/questions/20887555/dead-simple-example-of-using-multiprocessing-queue-pool-and-locking). I thinking remove a dependency for `cdp`, and hence `e3sm_diags` would reduce some work needed in the E3SM-Unified env.

**Comment by chengzhuzhang** [comment]
@zshaheen Thank you for looking into it. Yes, I have looked at the implementation of multiprocessing in CDP. I was also supersized about getting this error when using multiprocessing (**not** using distributed argument). I even suspect it's a dask issue. Thank you for weighing in.

**Comment by chengzhuzhang** [comment]
@xylar After you updated e3sm-unified using dask2.15.0. I re-tested @oksanaguba 's e3sm_diags run script and the error was gone :). Thank you!  https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/zhang40/test_2.1.0_oksana/viewer/
I just found one glitch that I forgot to bump up the version number to be displayed on the viewer, so v2.0.0 is still showing. I'm going to re-release 2.1.0. Let me know if it is okay, sorry about the inconvenience. .

**Comment by xylar** [comment]
@chengzhuzhang, it's better to do a new microrelease (2.1.1) or patch the existing release and do a new conda build than to replace a release.  If a release gets overwritten, there is no way to know what source code was used for a given build of a given release.

That being said, it's your repo and you can do what you want.  From my point of view, if you want to do a new build of 2.1.0 and upload to the e3sm channel, that's fine.  Just make sure to increment the build number.

**Comment by xylar** [comment]
Also, keep in mind that I already uploaded build 1 using the changes in https://github.com/E3SM-Project/e3sm_diags/pull/313 so you should upload build 2 (and then merge #313 soon, too!).

**Comment by xylar** [comment]
I believe I have figured out the solution to this issue.

I created a test environment from `master`:
```
conda create -y -n e3sm_diags_dev -c conda-forge -c defaults python=3.7 cdp cdms2 cdutil genutil \
    cdtime numpy matplotlib cartopy beautifulsoup4 lxml "dask==2.15.0"
conda activate e3sm_diags_dev
pip install .
```
and ran with the instructions at:
https://e3sm-project.github.io/e3sm_diags/docs/html/quickguides/quick-guide-cori.html
After commenting in the multiprocessing parameters, everything worked as expected (other than #338).

Then, I created the same environment but with the latest dask:
```
conda create -y -n e3sm_diags_latest_dask -c conda-forge -c defaults python=3.7 cdp cdms2 cdutil genutil \
    cdtime numpy matplotlib cartopy beautifulsoup4 lxml dask
conda activate e3sm_diags_latest_dask
pip install .
```
and ran as before.  I saw the `freeze_support()` error as above.

Then, I modified my run script as follows, following the instructions at https://github.com/dask/distributed/issues/2520:
```
#!/usr/bin/env python

import os
from acme_diags.parameter.core_parameter import CoreParameter
from acme_diags.run import runner

if __name__=='__main__':

    param = CoreParameter()

    param.reference_data_path = '/global/cfs/cdirs/e3sm/acme_diags/obs_for_e3sm_diags/climatology/'
    param.test_data_path = '/global/cfs/cdirs/e3sm/acme_diags/test_model_data_for_acme_diags/climatology/'
    param.test_name = '20161118.beta0.FC5COSP.ne30_ne30.edison'
    param.seasons = ["ANN"]   #all seasons ["ANN","DJF", "MAM", "JJA", "SON"] will run,if comment out"

    prefix = '/global/cfs/cdirs/e3sm/www/xylar/doc_examples_latest_dask/'
    param.results_dir = os.path.join(prefix, 'lat_lon_demo')
    # Use the following if running in parallel:
    param.multiprocessing = True
    param.num_workers = 32

    # Use below to run all core sets of diags:
    #runner.sets_to_run = ['lat_lon','zonal_mean_xy', 'zonal_mean_2d', 'polar', 'cosp_histogram', 'meridional_mean_2d']
    # Use below to run lat_lon map only:
    runner.sets_to_run = ['lat_lon']
    runner.run_diags([param])
```
Note: I'm just putting everything inside a `if __name__=='__main__':` conditional.  With that change, everything works fine.

I think the issue isn't necessarily with `dask` or `distributed`.  Instead, when multiprocessing is used in Python, I think it must call the original script again but not as a script (i.e. `__name__` is not `'__main__'`, it's something else).  I haven't looked into the details.

But my recommendation is to update the documentation and make an effort to make users aware of the change, and then we can go back to using the latest `dask`.  No changes to the code itself are likely needed.

**Comment by xylar** [comment]
I tested the fix (with a print statement on `__name__` just to see what happened) with the old dask (2.15.0) and everything still works fine, so the fix of adding `if __name__=='__main__':` is backwards compatible, as expected.

Interestingly, I didn't see any additional calls to the script with `__name__ == '__mp_main__'` so that seems to have been something that changed in dask 2.16.0.

**Comment by xylar** [comment]
I suspect this PR might be the cause of the change:
https://github.com/dask/dask/pull/4003

It looks like the default multiprocessing context changed from `fork` to `spawn` in that PR.  Presumably, explicitly setting the context to `fork` would get the old behavior back.  I believe this would require modifying this line in `cdp`:
https://github.com/CDAT/cdp/blob/master/cdp/cdp_run.py#L22
to be:
```
with dask.config.set({'scheduler': 'processes', 'multiprocessing.context': 'fork'):
```
I can do a test build of `cdp` and see if that's the case.

**Comment by xylar** [comment]
I put in PRs:
https://github.com/CDAT/cdp/pull/53
and
https://github.com/E3SM-Project/e3sm_diags/pull/339
to fix this using the approach of hard coding "fork" as the multiprocessing context in `e3sm_diags`.  If you later wanted to support the default "spawn", you could either remove specification of the context or allow users to choose.

**Comment by chengzhuzhang** [comment]
Hi @xylar, nice discovery on the Dask discussion regarding to switch the default multiprocessing contest! And thank you for working on this issue. I think the PR in cdp looks good and the suggestion on also note to the users on adding `if __name__=='__main__':` in their run script makes sense. 

However one of the concerns with changing `cdp` is that, it is also a dependency of another diagnostics software `[pmp](https://github.com/PCMDI/pcmdi_metrics)` (PCMDI's Metrics package). And I think multiprocessing is also used in `pmp`. We should make sure the change won't break `pmp`, before updating `cdp`.

**Comment by xylar** [comment]
I did look a little at the `pcmdi_metrics` repo and documentation.  As far as I can tell, the documentation is not consistent with the current state of the package.  But it looks like the driver scripts that `pcmdi_metrics` uses are not using `if __name__=='__main__':`, at least not consistently.  So I believe they will have this same problem with `dask >= 2.16.0`.  Perhaps no one has tried to run with it yet?  The only `meta.yaml` file I could find was still using `proj4` instead of `proj` and was over a year old, so it may be that a lot would need to be done to make a build with current `conda-forge` pins.
