### ISSUE TITLE
Empty Polar maps in v2.1.0

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#318]
Reported by @wlin7 and @darincomeau, Polar maps are empty in v2.1.0. The problem is reproduced in v2.1.0 and e3sm_unified 1.3.1 by following: 
```
e3sm_diags polar --no_viewer --case_id 'GPCP_v2.3' --sets 'polar' --run_type 'model_vs_obs' --variables 'PRECT' --seasons 'ANN' --regions 'polar_S' --regrid_tool 'esmf' --regrid_method 'conservative' --main_title 'PRECT ANN polar_S' --backend 'mpl' --output_format 'png' --canvas_size_w '1212' --canvas_size_h '1628' --figsize '8.5' '11.0' --dpi '150' --arrows --contour_levels '0.5' '1' '1.5' '2' '2.5' '3' '3.5' '4' '4.5' '5' --test_name '20190306.A_WCYCL1850-DIB-ISMF_CMIP6.ne30_oECv3wLI.edison' --test_colormap 'WhiteBlueGreenYellowRed.rgb' --ref_name 'GPCP_v2.3' --reference_name 'GPCP' --reference_colormap 'WhiteBlueGreenYellowRed.rgb' --diff_title 'Model - Observation' --diff_colormap 'BrBG' --diff_levels '-2' '-1.5' '-1' '-0.75' '-0.5' '-0.25' '0.25' '0.5' '0.75' '1' '1.5' '2' --num_workers '4' --granulate 'variables' 'seasons' 'plevs' 'regions' --selectors 'sets' 'seasons' --reference_data_path '/global/cfs/cdirs/e3sm/acme_diags/obs_for_e3sm_diags/climatology/' --test_data_path '/global/cfs/cdirs/m3412/atm_climo/20190306.A_WCYCL1850-DIB-ISMF_CMIP6.ne30_oECv3wLI.edison/yrs71-100' --results_dir '/global/cfs/cdirs/e3sm/www/zhang40/tests'
```
Resulting:
![GPCP_v2 3-PRECT-ANN-polar_S](https://user-images.githubusercontent.com/13056557/88762320-d07bf080-d125-11ea-9c9d-0a11f0887b70.png)

**Comment by chengzhuzhang** [comment]
After some trouble shooting, the problematic line of code is `ax.set_boundary(circle, transform=ax.transAxes)` from: https://github.com/E3SM-Project/e3sm_diags/blob/master/acme_diags/plot/cartopy/polar_plot.py#L82

This line is to set the boundary of the plot to be a circle (from a square). The implementation was straightly followed the cartopy example:https://scitools.org.uk/cartopy/docs/latest/gallery/always_circular_stereo.html

This problem is only re-producible from cartopy0.18.0 which was released recently (May 2020). I suspect this is an cartopy issue. @golaz and @forsyth2 I would intend to roll back to cartopy0.17.0 or earlier to fix this bug and at a same time file an issue to cartopy team. Let me know what you think. This bug was initially reported by users of latest e3sm_unified just recently deployed, we will have to get @xylar 's help on a fix for e3sm_unified. I should have tested more rigorously using an updated environment...

**Comment by xylar** [comment]
@chengzhuzhang, we worked very hard to get MPAS-Analysis working with cartopy 0.18.0 and it does not work correctly with earlier versions.  So we are not able to roll back to the earlier version in E3SM-Unified without breaking MPAS-Analysis.  Could it be that syntax has changed or something like that?  I think it would be worth trying to see if 0.18.0 can be made to work.  Otherwise, we cannot have MPAS-Analysis and E3SM-Diags in the came conda environment.

**Comment by xylar** [comment]
For some context, here is the PR related to switching to `cartopy` in MPAS-Analysis that took us a year and a half to finally get done: https://github.com/MPAS-Dev/MPAS-Analysis/pull/497

**Comment by xylar** [comment]
I worked on this for a couple of hours.  I'm able to reproduce this by just adding a `contourf` plot to the example at https://scitools.org.uk/cartopy/docs/latest/gallery/always_circular_stereo.html
So I completely agree that this is a `cartopy` issue.  We seem to be at something of an impasse because MPAS-Analysis requires cartopy >= 0.18.0 but E3SM-Diags needs cartopy < 0.18.0.  The only solution I can come up with is for E3SM-Diags to temporarily comment out the `ax.set_boundary()` call and live with the square polar stereographic plots until a fix for `cartopy` is available and a new version has been released.  But I'm open to other suggestions.

**Comment by xylar** [comment]
I posted an issue on the `cartopy` repo: https://github.com/SciTools/cartopy/issues/1620

**Comment by chengzhuzhang** [comment]
Thank you for helping trouble shooting and filing an issue on `cartopy`. Currently, @wlin7 rolled back to e3sm_unified1.3.0 in order to generate the polar view plots. The post-processing workfrom @golaz uses requires calling e3sm_diags and mpas-analysis from a single e3sm_unified env, i will defer to Chris on a pathforward on this. I think commenting out the `ax.set_boundary()` to have a square figure could be an okay work around.

**Comment by chengzhuzhang** [comment]
@xylar Depending on a solution of this issue, with regarding to the stand-alone `e3sm_diags` env, I will look to put `cartopy <=0.17.0`(or not if a square figure for polar projection is accepted) and `dask <=2.15` for an updated `meta.yml` and pinned version of yaml files`e3sm_diags_env*.yml`

**Comment by golaz** [comment]
We should switch to square plots if that solves the problem. Round plots were only selected initially to match AMWG. There is nothing wrong with square plots. We should really avoid using different versions of `cartopy` for MPAS-Analysis and E3SM Diags.

**Comment by chengzhuzhang** [comment]
Thank you @golaz. Below is a comparison between circular boundary and square boundary (with the `set_boundary` line commented out). I'm going to issue a PR and release a new micro release of e3sm_diags.
![ERA-Interim-T-850-ANN-polar_S](https://user-images.githubusercontent.com/13056557/88959528-fead1d80-d256-11ea-9e9e-5f6415677d5a.png)

![ERA-Interim-T-850-ANN-polar_S](https://user-images.githubusercontent.com/13056557/88959580-12588400-d257-11ea-9126-75ad76072455.png)

**Comment by chengzhuzhang** [comment]
This is only a workaround not real fix. will keep this open for a while.

**Comment by chengzhuzhang** [comment]
Fixed in https://github.com/E3SM-Project/e3sm_diags/pull/336
