### ISSUE TITLE
Not able to create a dev environment following docs

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#319]
I'm not able to able to follow the instructions for creating an environment using the file https://github.com/E3SM-Project/e3sm_diags/blob/master/conda/e3sm_diags_env_dev.yml
`conda create` produces the usual unhelpful message about conflicts:
```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
- failed
```
It seems maybe the `yaml` file needs to be updated.

**Comment by xylar** [comment]
The following, pulled form `meta.yaml`, works fine and is maybe more robust over the long run than the `yaml`:
```
conda create -y -n e3sm_diags_env_dev -c cdat/label/v82 conda-forge defaults python=3.7 "cdp>=1.60" "vcs>=8.2" \
  "vtk-cdat=8.2.0.8.2" "vcsaddons>=8.2" "dv3d>=8.2" "cdsm2>=3.1.4" "cdutil>=8.2" "genutil>=8.2" "cdtime>=3.1.2" \
  numpy matplotlib "cartopy=0.18.0" beautifulsoup4 lxml
```

**Comment by chengzhuzhang** [comment]
@xylar I have a PR for fixing ymls. We had installations being unstable using a single `conda create` command and later started to support ymls where the version of dependencies are pinned down. However, as you noted, these ymls need to be maintained periodically. I agree in the long run, using the `conda create` line could be more robust.
