### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#343]
In https://e3sm-project.github.io/e3sm_diags/docs/html/input-data-requirement.html:

1. Replace `ncclimo -s start_yr -e end_yr -c run_id -i drc_in -o drc_out` with `ncclimo -s start_yr -e end_yr -c run_id -i drc_in -o drc_out -r map_fl -O drc_rgr -a sdd --no_amwg_links`.
2. Add `--drc_rgr=$drc_rgr` following every instance of `--drc_out=$drc_out`.

In https://e3sm-project.github.io/e3sm_diags/docs/html/dev_guide/releasing-e3sm-diags.html: add the section "Updating The sha256" from zstash docs (https://e3sm-project.github.io/zstash/docs/html/release.html#updating-the-sha256)

**Comment by forsyth2** [comment]
Merge before #299 so that the docs for the latest release include these changes.

**Comment by chengzhuzhang** [comment]
Thank you for taking care of this!

**Comment by forsyth2** [comment]
#345 merging should have closed this.
