### ISSUE TITLE
scipy is missing from last release 

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#353]
e3sm_diags_env.yml and e3sm_diags_env_dev.yml are fine. meta.yml needs to be updated.

**Comment by xylar** [comment]
It could be that it was coming in via `cartopy` but we changed `cartopy` to not require `scipy`, since it works without it.  Anyway, it's always best to be explicit about dependencies.  `mpas_tools` had a similar issue with `pyproj`.

**Comment by chengzhuzhang** [comment]
Thanks, it makes sense. I was guessing if the removal of vtk_cdat caused this. A little unexpected but I agree to be explicit about dependencies.

**Comment by chengzhuzhang** [comment]
fixed in https://github.com/E3SM-Project/e3sm_diags/pull/362.
