### ISSUE TITLE
Update CI/CD workflow to single service

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#384]
The CI/CD build for both CircleCI and TravisCI is currently failing on `master`. This is a blocker for automating docs using CI/CD (#377). 

Problems
---
1. CircleCI [pipelines](https://app.circleci.com/pipelines/github/E3SM-Project/e3sm_diags) outputs the error below:
```
No .circleci/config.yml was found in your project. Add a configuration file to your repository or refer to documentation.
```
Solution: 
We only need one CI/CD service. According to this [comment](https://github.com/E3SM-Project/e3sm_diags/issues/363#issuecomment-739129557), CircleCI was used for testing Mac and TravisCI for Linux. However, separate testing is no longer necessary for Mac.

We should adopt an alternative CI/CD service (CircleCI, GitHub Actions) and purge TravisCI. TravisCI has a new pricing model and is no longer providing CI minutes for open source software.
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> - For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> You will not need to change your build definitions when you are pointed to the new plan
> - When your credit allotment runs out - we'd love for you to consider which of our plans will meet your needs.
> 

2. For TravisCI, the [build log](https://travis-ci.org/github/E3SM-Project/e3sm_diags/builds/756785666) show that it starts failing on PR #375  which includes `test_complete_run.py`. 

**UPDATE: FIXED BY #383** 

I think it was accidentally included in the build’s test runner because there is a comment at the top:.

```
# Due to the large amount of data required to run, this test will be run manually on Anvil
# (rather than as part of the CI tests).
```

From my experience using Pytest, if a test file’s name has a prefix of `test_`, then it will run automatically. 

Solution: Find a way to manually configure the `unittest` test runner to exclude `test_complete_run.py` This is typically done through a config file or as an argument on the command line (e.g. `--exclude test_complete_run.py`).

**Comment by rljacob** [comment]
We had to stop using TravisCI in the E3SM repo because they changed their pricing and no longer have a cap on free projects.

**Comment by tomvothecoder** [comment]
@rljacob Yeah, it looks like TravisCI's pricing model hasn't been good for open-source/free-tier projects due to the new limitations. I updated the issue description with a link to Google searches mentioning Travis CI no longer providing CI minutes for open source software.  It seems like TravisCI's popularity has decreased in recent years with the rise of other CI tools like CircleCI, GitHub Actions. 

@chengzhuzhang We might want to consider going back to CircleCI or use another service like GitHub Actions. Whichever one meets our requirements for the free-tier and is easiest to setup and maintain. I'll scope these services out for our use case.

**Comment by chengzhuzhang** [comment]
How the pricing change of Travis-CI will affect small repos? It runs okay for now. Is there a deadline that they will discontinue service?

**Comment by zshaheen** [comment]
As per @xylar's [comment here](https://github.com/E3SM-Project/e3sm_diags/issues/363#issuecomment-739148953), the MPAS team moved over to Azure Pipelines. You might want to look into that.

Also, the only reason we used CircleCI was because testing on macOS was free.  It's your call, but personally don't think that testing on macOS is even needed.

**Comment by tomvothecoder** [comment]
@zshaheen Thanks for clarifying on why CircleCI was used alongside TravisCI!

> How the pricing change of Travis-CI will affect small repos? It runs okay for now. Is there a deadline that they will discontinue service?

@chengzhuzhang I updated the issue description and sent you a Slack message. We should consider moving to an alternative service before our TravisCI credit runs out. I'm going to try out GitHub Actions since I've had good experience using it.

**Comment by xylar** [comment]
@tomvothecoder and @chengzhuzhang, let me know if you decide GitHub Actions won't do what you need and want to try Azure Pipelines.  Either way, if you want help with building the documentation automatically for each PR and tag, and uploading it to GitHub-Pages, let me know.

**Comment by tomvothecoder** [comment]
Thanks @xylar!
