### ISSUE TITLE
Better developer documentation for piece that generates HTML

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#413]

**Comment by chengzhuzhang** [comment]
Hey Tom, I was able to follow this notebook to generate ARM-diags viewer. https://github.com/CDAT/cdp/blob/master/jupyter/using-the-cdp-viewer.ipynb. It seems straightforward to follow. I'm thinking for v2.5.0, we can add an example based on this notebook to developers documentation.

**Comment by tomvothecoder** [comment]
@chengzhuzhang Thanks Jill, I'll base the example off of that source
