### ISSUE TITLE
CDAT Migration Phase 1: Replace `cdp.cdp_run`

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#426]
As mentioned on #425, it may be a good idea to write our own multiprocessing code rather than using the `cdp` code. This would allow us to write finer-grained error messages (such as which sets in particular failed).

**Comment by tomvothecoder** [comment]
Related to https://github.com/E3SM-Project/e3sm_diags/pull/425#issuecomment-809575961
