### ISSUE TITLE
Fix failing parameters on v2_4_0 tutorial

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#427]
While working on #425, it became apparent that ENSO diags in https://github.com/E3SM-Project/e3sm_diags/blob/master/examples/tutorials/tutorial_v2_4_0_all_sets_E3SM_machines.py was only completing 9 out of 12 parameter runs. Three fail:

- `RuntimeError: Neither does TAUY nor the variables in [('tauv',)] have valid files in /lcrc/group/e3sm/public_html/e3sm_diags_test_data/time-series/E3SM_v1/.`
- `RuntimeError: Neither does TAUX nor the variables in [('tauu',)] have valid files in /lcrc/group/e3sm/public_html/e3sm_diags_test_data/time-series/E3SM_v1/.`
- `RuntimeError: Neither does TAUX nor the variables in [('tauu',)] have valid files in /lcrc/group/e3sm/public_html/e3sm_diags_test_data/time-series/E3SM_v1/.`

**Comment by chengzhuzhang** [comment]
Do TAUY and TAUX exist in time series folder? If they are not, reporting error is expected behavior.

**Comment by forsyth2** [comment]
No, they aren't present in that directory. But it would be better to direct the tutorial either 1) to use TAUX/TAUY data from elsewhere or 2) to skip anything involving TAUX/TAUY data. I don't think it's good for our tutorial to have any errors reported in the output, considering that it might confuse users.

**Comment by chengzhuzhang** [comment]
In this case, option 1 sounds like a better solution, we would want to generate TAUY and TAUX monthly series from 1980 to 2014 from simulation 20180215.DECKv1b_H1.ne30_oEC.edison. And place them in directory monthly_ts/20180215.DECKv1b_H1.ne30_oEC.edison/1980-2014/rgr/

**Comment by forsyth2** [comment]
In addition to these failures, `CoreParameter` has 4 failures of `OSError: No file found for HadISST and ANN in /lcrc/group/e3sm/public_html/diagnostics/observations/Atm/climatology/` and 4 failures of `OSError: No file found for HadISST and JJA in /lcrc/group/e3sm/public_html/diagnostics/observations/Atm/climatology/`.

**Comment by chengzhuzhang** [comment]
This SST message is documented here https://github.com/E3SM-Project/e3sm_diags/issues/338
Not sure how to get around..

**Comment by chengzhuzhang** [comment]
Fixed with TAUX and TAUY added.
