### ISSUE TITLE
Add tbump to simplify package versioning process

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#442]
Currently, we have to find the lines of code in different files and bump their versions manually. To make this process more automated, we can add [`bump2version`](https://github.com/c4urself/bump2version).

UPDATE: Using `tbump` instead

**Comment by xylar** [comment]
I was thinking about how to automate this process in my packages.  It didn't occur to me that there would already be a package for that but it makes sense!

**Comment by tomvothecoder** [comment]
UPDATE: `bump2version` does not support prerelease candidates (or at least without extensive hacking) at the moment. 
Related issue: https://github.com/c4urself/bump2version/issues/63

The alternative solution is using [`tbump`](https://github.com/dmerejkowsky/tbump).
