### ISSUE TITLE
Add conda channel label assignment in GH Actions release workflow

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#453]
Moving forward, all `e3sm_diags` conda builds will be published exclusively on `conda-forge`.
We also need to publish packages to specific labels based on the build type.

Requirements
- [ ] Production builds go to `conda-forge/main`.
- [ ] RC builds go to `conda-forge/rc`

**Comment by xylar** [comment]
As I mentioned elsewhere (https://github.com/E3SM-Project/zppy/pull/52#issuecomment-850534562), we don't actually want to be uploading `e3sm_diags` to the `e3sm` channel at all.  It can cause trouble to have different builds on `e3sm` and `conda-forge` channels of the same package (even if they are different versions).  Using strict channel order and putting conda-forge first will take care of this but our users don't always do that.  So I think we should remove `e3sm_diags` entirely from `e3sm` soon.  But at the very least, we don't want to upload any new versions there.

**Comment by xylar** [comment]
The good news is that the 2.4.0 package has been downloaded 0 times: https://anaconda.org/e3sm/e3sm_diags/files

**Comment by tomvothecoder** [comment]
@xylar Got it, all `e3sm-diags` builds will go to `conda-forge`.

`zppy` and `zstash` builds go to `e3sm/main` and their rc builds go to `e3sm/e3sm-dev`.
