### ISSUE TITLE
Set `CDMS_NO_MPI=True` 

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#465]
For e3sm_diags to work right in environments with `mpi4py` included, we need to wait for https://github.com/conda-forge/cdms2-feedstock/pull/68 to go in, then set `CDMS_NO_MPI=True`.  We could do that within e3sm_diags before all `import cdms` calls or we could require it to be set externally before calling `e3sm_diags`.  I'm not sure which way is best.  I can set that variable within the E3SM-Unified activation script, but that would still mean users that installed e3sm_diags themselves and also have `mpi4py` would need to know that they, too, need to set this variable.  Since we always want this behavior, it seems cleanest to me if `e3sm_diags` can handle it internally.  At the same time, checking an environment variable before an import is maybe considered sloppy form in python.

**Comment by tomvothecoder** [comment]
We can use a wrapper for libraries that need custom configuration.

So for `cdms2`, we can create a file call `acme_diags/cdms2.py` and replace all `cdms2` imports with it.

`acme_diags/cdms2.py`
 ```
import os

os.environ[“CDMS_NO_MPI”] = "True"
import cdms2
 ```

Files importing cdms2
```
import * from acme_diags.cdms2
```

Once question I have is whether we need the os variable as a boolean? Apparently `os.environ()` only supports string, which then needs to be converted to boolean.

**Comment by tomvothecoder** [comment]
A few things I noticed:

1. There's a lot of `import cdms2`, but only a few modules are actually used. It is more Pythonic to be explicit about the modules being used from a library in most cases.

2. There is a boolean constant called `HAVE_MPI` in some `cdms2` files, which imports `mpi4py` if true.
  In `cdms2`, the following files import from `mpi4py`
    * `setup.py`
    * `cdscan.py`
    * `dataset.py`
    * `tvariable.py` -- This is the only file `e3sm_diags` imports from that includes `mpi4py` 
    * `esmf.py`
    * `mvESMFRegrid.py`
    * And test files
     
    https://github.com/E3SM-Project/e3sm_diags/blob/4f14cf636484ee371b50f85c28aea5ea70faaa9b/acme_diags/acme_diags_driver.py#L32

**Can we leverage `HAVE_MPI` for the affected modules (just `tvariable` here), rather than using a global `CDMS_NO_MPI` env var?** I'm probably missing how `CDMS_NO_MPI` works though since I just started looking into this.

**Comment by chengzhuzhang** [comment]
Hey @tomvothecoder thank you for getting start on this. I'm pinging @jasonb5 on your question leveraging `HAVE_MPI`. Jason, would you recommend how to have `CDMS_NO_MPI` implemented in `e3sm-diags`?

**Comment by tomvothecoder** [comment]
I found the answer for `CDMS_NO_MPI` here: https://github.com/conda-forge/cdms2-feedstock/pull/68/commits/d82ae7aeb62586f99fb85aee6d4b0a7bfa21ac4c

Also, I noticed `getenv_bool` is used to typecast `CDMS_NO_MPI` to a boolean.

Basically, it looks like my solution above might work!

**Comment by xylar** [comment]
> `import * from acme_diags.libs.cdms2`

If you feel like this is the best way, that's fine.  As a developer, I always find `import *` commands frustrating because I never know what comes in with those commands.

**Comment by tomvothecoder** [comment]
@xylar I agree, it's not good practice to `import *`.

I found that `os.environ["CDMS_NO_MPI"]` still gets set with `from acme_diags.libs.cdms2 import cdms2`, which is much better.

**Comment by xylar** [comment]
Oh, great, I think that's much better then.
