### ISSUE TITLE
Require output_viewer >=1.3.3?

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#469]
In E3SM-Unified, I'm running into issue https://github.com/E3SM-Project/e3sm_diags/issues/342 fixed by https://github.com/ESGF/output_viewer/pull/18.  This is because we're using `output_viewer` 1.3.1. I would argue that either `cdp` or `e3sm_diags` now needs `output_viewer >=1.3.3` in its conda-forge recipe.  Since `output_viewer` isn't a direct dependency of `e3sm_diags`, maybe it doesn't make sense for it to still be in the `meta.yaml`?  But that's only if `cdp` can be modified to constrain the version as `e3sm_diags` needs.  We should just updated the version constraint.

Depending on what is done above, it also might be important to include `output_viewer` in the other YAML files because it should be constrained to 1.3.3.

**Comment by xylar** [comment]
I'm also working on fixing the fact that `output_viewer` 1.3.3 is currently pinned to `python <3.8`, which is a problem for E3SM-Unified: https://github.com/conda-forge/output_viewer-feedstock/pull/10

**Comment by chengzhuzhang** [comment]
Hey @tomvothecoder would you please take care of this? Also can we switch to use python 3.8 for CI?

**Comment by tomvothecoder** [comment]
@chengzhuzhang Sure, so my actions are:
1. Update to `output_viewer >=1.3.3` in `meta.yaml`
2. Update to `Python>=3.9`(based on #468) in conda env files

**Comment by chengzhuzhang** [comment]
Sounds good. If movinng to 3.9 cause to many conflict, we can roll back to 3.8
