### ISSUE TITLE
Remove `docs/_build_old` with `v2.3.0` and `v2.4.0` docs

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#478]
We can remove the `docs/_build_old` directory since E3SM unified is being released with `v2.5.0`, 

This directory stored old doc builds that existed on the `gh-pages` branch before #352 and #377.

**Comment by chengzhuzhang** [comment]
Hey Ryan, I still like to access some old docs from time to time. Does this PR remove them?

**Comment by tomvothecoder** [comment]
Hi Jill, I think you meant to ask me that question. Yes, this PR removes the old builds from `master`.

A workaround is to checkout a commit that contains the old doc builds (e.g., the commit before this PR is merged). You can  create a local branch from this commit  and name it something like `v2.3.0_v2.4.0_docs`. You checkout this branch for times when you need to reference the old docs.

In addition to #306, it would be a good idea to remove old builds from `master` to reduce the repo size.

**Comment by chengzhuzhang** [comment]
Got it! I just made a v2.3.0_v2.4.0_docs branch so that old builds can be referred later. I'm about to release a `rc3` today, do you like to have this issue fix to be included in `rc3`?

**Comment by tomvothecoder** [comment]
Sorry Jill, I was out on Friday so I didn't see your question. We can include it in the final release of `v2.5.0` since it doesn't need to be tested.
