### ISSUE TITLE
The python package includes the `tests` directory 

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#484]
The line:
https://github.com/E3SM-Project/e3sm_diags/blob/14d7c969305098f0a3ea582ad6a3395c864ae558/setup.py#L118
seems designed to exclude tests but it doesn't actually have the `tests` directory in its excludes.  As a result, it ends up in the conda package and it conflicts with other packages that make the same mistake (e.g. `zppy` and `zstash`).

Instead, it would be much cleaner and safer to do:
```
packages=find_packages(include=['acme_diags', 'acme_diags.*'])
```

**Comment by chengzhuzhang** [comment]
Hey @tomvothecoder would you please also help fixing this?

**Comment by tomvothecoder** [comment]
Sure thing, I'm helping out Ryan on the same issue on `zstash` so I'm familiar with it.
