### ISSUE TITLE
Pressure-Latitude zonal mean contour plots don't cover stratosphere

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/e3sm_diags#492]
The plots currently stop at 100 hPa, not covering the stratosphere. The stratospheric model results are important. In particular, the T in the southern polar region is useful to determine the ozone hole PSC T threshold. If the observational and difference plots cannot be extended, we at least need to plot the stratospheric model results.

**Comment by chengzhuzhang** [comment]
Hey @tangq yes, we can extend the pressure level higher to visualize stratosphere. The observation data we use for pressure -latitude zonal mean contour plots, MERRA2 and ERA-Interm both stops higher than 100 hPa, i.e. ERA-interim to 1 hPa and MERRA2 stops at 0.1hPa. With that, we can just do extension in pressure levels. Would you share an example figure or specs for pressure levels (i.e., where it should stop?, and use logrithmic axis? and so on) to best visualize stratospheric features.

**Comment by tangq** [comment]
@chengzhuzhang , you can see the Fig. 1 of this paper https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019MS001763 for an example. Stopping at 1 hPa (start at 100 hPa) and with a logarithmic vertical axis to show the stratosphere.

For the troposphere, a linear vertical axis is actually better. Can you separate the axis scales at 100 hPa, like merging two plots together? I've seen similar plots before, but couldn't find it off hand.

Alternatively, we can have a separate set for the stratosphere. For that, we would like some overlap between the trop and strat sets - trop stops at 50 hPa; strat starts at 150 hPa.
