### ISSUE TITLE
Update unified paths in docs

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#493]
`activation_command` paths on https://e3sm-project.github.io/e3sm_diags/_build/html/master/quickguides/quick-guide-general.html should be updated to match those on https://e3sm-project.github.io/zppy/_build/html/main/getting_started.html

**Comment by forsyth2** [comment]
@chengzhuzhang #510 resolves this issue for the `master` docs. Do we also want to update the v2.5.0 docs since v2.5.0 is available in the latest Unified? Ideally we would, but it is a very tedious process to update old versions of the docs.

It wouldn't be so bad if it was just adding the machine names to the existing Unified paths, but #510 changed some file names and split LCRC references into Chrysalis and Anvil references, which will be more difficult to change directly in the HTML.

**Comment by chengzhuzhang** [comment]
I think we don't worry about patch old docs, as long as we keep the master up to date. It seems like Chrysalis and Anvil guide should be basically the same, one can activate either the Chrysalis or Anvil `e3sm_unified` env from both machines?

**Comment by forsyth2** [comment]
Sounds good. 

Yes, they are effectively the same except for the Unified path, but it would have been more difficult to create a single auto-generated "LCRC" page that listed two possible paths than to just auto-generate two distinct pages.

**Comment by chengzhuzhang** [comment]
Got it, thanks!
