### ISSUE TITLE
Fix automating docs with `sphinx-multiversion` and needing to manually fix HTML builds for tag releases

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#499]
Overview:
* `sphinx-multiversion` generates doc builds on `gh-pages` for `master` and all tag releases (e.g., `v2.5.0`)
* `sphinx-multiversion` **adds a statically generated chunk of HTML for the version selector dropdown to ALL of the HTML pages in ALL doc builds**.

```
<div class="rst-versions" data-toggle="rst-versions" role="note" aria-label="versions">
  <span class="rst-current-version" data-toggle="rst-current-version">
    <span class="fa fa-book"> Other Versions</span>
    v: master
    <span class="fa fa-caret-down"></span>
  </span>
  <div class="rst-other-versions">
    <dl>
      <dt>Tags</dt>
      <dd><a href="../v2.5.0/available-parameters.html">v2.5.0</a></dd>
    </dl>
    <dl>
      <dt>Branches</dt>
      <dd><a href="available-parameters.html">master</a></dd>
    </dl>
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/25624127/127931278-7cd312b5-d267-4a3d-a17a-88a3c070094d.png)

The problem: 
* The version dropdown is not dynamic. If we release a new tag, we have to regenerate ALL docs so that `sphinx-multiversion` can capture the tag in the dropdown.

What this means:
* We can't manually add HTML fixes in `gh-pages` for builds and also have the version selector dropdown be up to date

Potential solutions
1. Remove `sphinx-multiversion` entirely and manually add hyperlinks for documentation versions
2. Release patch versions with doc fixes
   - I'm sure a lot of folks run into situations where they find errors in the docs after already releasing them, so they use patching. There's basically no going back to manually fix HTML builds if you're automating docs. 
   - We probably don't need to release a new Anaconda version for a patch version if there are only doc updates. 
   - We have to make the difference in patch version highly visible to the end user if we don't release a new Anaconda version.

**Comment by tomvothecoder** [comment]
@forsyth2 @chengzhuzhang @xylar 

Some discoveries as we deal with fixing typos (https://github.com/E3SM-Project/zppy/pull/109) for `zppy` `v1.0.0` and accidentally removing `.png` files `v2.5.0` docs due to e3sm-diags file purge (#496).

There is no easy way I can think of to fix these problem without removing automation of docs or rereleasing tags.

**Comment by forsyth2** [comment]
> There is no easy way I can think of to fix these problem without removing automation of docs or rereleasing tags.

I think releasing a new patch version (e..g, E3SM Diags v2.5.1 or `zppy` v1.0.1) would be reasonable. The only problem I foresee is that a user might go to the v1.0.0 docs not realizing the v1.0.1. docs have more info.

**Comment by chengzhuzhang** [comment]
I do hope we can keep the docs generation automated. New releases sounds reasonable to me. For docs, I often think it is more important to keep docs on master up-to date. It is not thorough, but may not worth too much effort to patching old docs.

**Comment by tomvothecoder** [comment]
For e3sm-diags `v2.5.0`, it will always not have images if we keep automation, so we don't need a patch. The user can just use `master` as @chengzhuzhang mentioned.

I agree with @forsyth2 with patching if it makes sense, such as if the doc presents major info errors or typos with wrong paths.

**Comment by xylar** [comment]
> For docs, I often think it is more important to keep docs on master up-to date. It is not thorough, but may not worth too much effort to patching old docs.

The problem is that the correct documentation for `master` may begin to diverge pretty significantly from the release that is in E3SM-Unified.  If that happens, the "right" thing to do is to point users to the documentation for the 2.5.0 release if they are using E3SM-Unified.  But if **no** documentation actually tells users what they need to do in E3SM-Unified, we're in pretty serious trouble.  That's why I think manually updating existing documentation is better.

Even if you were to to a 2.5.1 release to patch the documentation, it would be really confusing to tell users that they need to look at the 2.5.1 documentation to find out about the 2.5.0 release in E3SM-Unified. Certainly, no one would realize that on their own.

I'm really excited to have learned about `sphinx-multiversion`!  I have been doing a manual version page in our docs for the 5 python packages I maintain and it's a pain.  But it seems like the automation with `sphinx-multiversion` comes with restrictions that are maybe too burdensome if there is no way to manually patch old documentation without disrupting automation.

Maybe this is what @tomvothecoder already figured out.  Maybe as long as you only delete and remake the docs associated with `master`/`main`, and leave tagged versions in place rather than recreating them, this can work?  Or does `sphinx-multiversion` then not handle the version selector dropdown correctly?

**Comment by tomvothecoder** [comment]
> The problem is that the correct documentation for master may begin to diverge pretty significantly from the release that is in E3SM-Unified. If that happens, the "right" thing to do is to point users to the documentation for the 2.5.0 release if they are using E3SM-Unified. But if no documentation actually tells users what they need to do in E3SM-Unified, we're in pretty serious trouble. That's why I think manually updating existing documentation is better.

Yup, I agree on the potential divergence with `master` and a specific version. In our case, `master` is actually a `development` branch, so users shouldn't expect the information to be consistent with their version (even if we assume no breaking changes between minors and patches).

> Even if you were to to a 2.5.1 release to patch the documentation, it would be really confusing to tell users that they need to look at the 2.5.1 documentation to find out about the 2.5.0 release in E3SM-Unified. Certainly, no one would realize that on their own.

I also agree with users getting confused if we don't keep the E3SM-unified package version and docs aligned. To mitigate some confusion, we would need a highly visible changelog between the versions. Not the prettiest solution though.

---
Tools like `sphinx-multiversion` and ReadTheDocs are great for automating docs. The "caveat" (actually an expected behavior) with these automation tools is that it builds docs using source files pushed in a tag. That means the source for docs must not have errors, or else you need to release a new patch tag with doc fixes.

In our case, `sphinx-multiversion` has to regenerate all docs every time a new tag is released so that the dropdown populates with the new tag, otherwise it will be outdated.

> Maybe this is what @tomvothecoder already figured out. Maybe as long as you only delete and remake the docs associated with master/main, and leave tagged versions in place rather than recreating them, this can work? Or does sphinx-multiversion then not handle the version selector dropdown correctly?

Yup, automation and manual HTML fixes aren't possible unless you develop your own doc automation tooling. 

That solution was implemented in PR #498 to allow manual HTML updates. The tradeoff is the version dropdown selector being outdated for older tag releases. 

Here's a visual example to make things clearer:
```
1. `master` -> links to `v2.5.0 and `v2.6.0` (and all subsequent releases automatically)
2. `v2.6.0` -> links to `master` and `v2.5.0` (does not link to subsequent releases automatically)
3. `v2.5.0` -> links to `master (does not link to subsequent releases automatically)
```

If everyone agrees that PR #498 is good middle-ground solution between automating and manual HTML fixes, we can move forward to integrate it in `zppy`.

**Comment by xylar** [comment]
@tomvothecoder, that's a really helpful summary. I can see why all versions need to be rebuilt when each new version is added or updated.

Your "middle-ground" solution does seem like the best solution.  I wish we were better in general at having flawless documentation with each of our releases but issues are unfortunately not that uncommon.  The risk of having version links that aren't quite right seems the smaller inconvenience to me.

**Comment by forsyth2** [comment]
> 1. `master` -> links to `v2.5.0 and `v2.6.0` (and all subsequent releases automatically)
> 2. `v2.6.0` -> links to `master` and `v2.5.0` (does not link to subsequent releases automatically)
> 3. `v2.5.0` -> links to `master (does not link to subsequent releases automatically)

I'm a little confused by this. I think this means in the `v2.5.0` docs, the only link in the dropdown selector is `master`, in the `v2.6.0` docs, the two links in the dropdown selector are `master` and `v2.5.0`, and in the `master` docs, there are three links in the dropdown selector (`master`, `v2.6.0`, `v2.5.0`). Is that correct?

**Comment by tomvothecoder** [comment]
@forsyth2 Correct, the dropdown also has a link to itself for whatever version of docs you're on.

![image](https://user-images.githubusercontent.com/25624127/128057769-ea6abf3b-b723-43bd-a6d6-abf4ae500653.png)

**Comment by chengzhuzhang** [comment]
Hi Tom. I agree with Xylar your solution sounds like the best option right now. Thank you for the research!

**Comment by tomvothecoder** [comment]
Cool, glad we have a workaround!

@chengzhuzhang, if there are issues with docs for released tags, you can checkout the `gh-pages` branch and push manual HTML fixes as needed.

**Comment by chengzhuzhang** [comment]
Awesome. Thank you, Tom!
