### ISSUE TITLE
Plot title overlaps with units

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#501]
In some plots in the zppy tests, the plot title overlaps with the units. For example: https://web.lcrc.anl.gov/public/e3sm/zppy_test_resources/expected_complete_run/e3sm_diags/180x360_aave/model_vs_obs_0001-0020/viewer/lat_lon/gpcp_v22/prect-global-gpcp_v22/ann.html.

**Comment by chengzhuzhang** [comment]
e3sm-diags has a parameter `short_test_name` to avoid this situation (test name too long and overlaps with units). I think that was set in some zppy configuration. But not in this particular example.

**Comment by forsyth2** [comment]
@chengzhuzhang If that's the preferred solution I can update the `zppy` tests then and close this issue.  I'm not sure if there's a way to avoid the overlap in all cases but if so, that might be good to implement.

**Comment by chengzhuzhang** [comment]
e3sm-diags has a parameter `short_test_name` to avoid this situation
