### ISSUE TITLE
Quick starts need to be updated the README.md

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#502]
I would have expected to find a link to Anvil/Chrysalis or LCRC among the quick starts in:
https://github.com/E3SM-Project/e3sm_diags/blob/cb58a00e69fcc8fb372d741061fb414cd71f2f94/README.md

Also, the link to Rhea is broken and should be removed (or replaced with one for Andes).  The Edison link is clearly long out of date, no link is available for Compy.  AIMS4 is probably not supported.

In general, it might be best to just link to the documentation and not maintain redundant documentation in the README.md.

**Comment by chengzhuzhang** [comment]
Resolved. Thank you for reporting.
