### ISSUE TITLE
Add symlink from `acme_diags` to `e3sm_diags` on servers

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#505]
Related to #495 

Examples from docs:
```
# Before
    reference_data_path = '/global/cfs/cdirs/e3sm/acme_diags/obs_for_acme_diags/'
    test_data_path = '/global/cfs/cdirs/e3sm/acme_diags/test_model_data_for_acme_diags/'

# After
    reference_data_path = '/global/cfs/cdirs/e3sm/e3sm_diags/obs_for_acme_diags/'
    test_data_path = '/global/cfs/cdirs/e3sm/e3sm_diags/test_model_data_for_acme_diags/'
```

**Comment by chengzhuzhang** [comment]
It turned out, only e3sm_diags reference data path on Cori needs a name update.
The `/global/cfs/cdirs/e3sm/acme_diags/` is now renamed to `/global/cfs/cdirs/e3sm/e3sm_diags/`
a symlink is created with `ln -s /global/cfs/cdirs/e3sm/e3sm_diags /global/cfs/cdirs/e3sm/acme_diags`
