### ISSUE TITLE
Automate quick guide generation

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#509]
Move the `python source/quickguides/generate_quick_guides.py # Run if quick-guide files were updated` step on `docs/source/contributing.rst` into the automated documentation building (probably at https://github.com/E3SM-Project/e3sm_diags/blob/master/.github/workflows/build_workflow.yml#L128?)

The correct workflow currently is the following:
1. Modify `docs/source/quickguides/generate_quick_guides.py` and/or `docs/source/quickguides/generate_quick_guides.py`
2. Run `python docs/source/quickguides/generate_quick_guides.py` to generate:
  - `docs/source/quickguides/quick-guide-acme1.rst`
  - `docs/source/quickguides/quick-guide-compy.rst`
  - `docs/source/quickguides/quick-guide-cori.rst`
  - `docs/source/quickguides/quick-guide-lcrc.rst`

However, those four generated files currently exist in the repo. They can be (and have been) edited independently, which disrupts the above workflow. It would be better for those generated files to not exist in the repo and have the automated documentation handle the file generation.

**Comment by forsyth2** [comment]
@tomvothecoder Is addressing this as simple as adding `python source/quickguides/generate_quick_guides.py` after https://github.com/E3SM-Project/e3sm_diags/blob/master/.github/workflows/build_workflow.yml#L128?

**Comment by chengzhuzhang** [comment]
The lcrc quick guide is missing on master doc: https://e3sm-project.github.io/e3sm_diags/_build/html/master/index.html Just want to make sure they will be brought back by this PR. Also the links to Crysalis and Anvil need to update in README due to the split of LCRC quickguide.

**Comment by forsyth2** [comment]
@chengzhuzhang Thanks, yes I'm discovering that in testing this PR. I'll be sure to fix that before merging!

**Comment by forsyth2** [comment]
Closed #511 in favor of #513, which still fixes the errors mentioned above.
