### ISSUE TITLE
Tropical Cyclone images not showing up with development environment

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#520]
As discussed in #514, Tropical Cyclone images do not show up with development environment. 4 out of 6 images show up in the `tc_analysis` subdirectory; the 2 maps do not. Furthermore, the TC diagnostics do not show up in the viewer. However, using the Unified environment, all 6 images are present and the TC diagnostics shows up in the viewer.

**Comment by chengzhuzhang** [comment]
I'm running TC analysis on Chrysalis and it turned out that I have the same issue only 4 out of 6 images created. I do have error message suggested that the rest of two plots, which are maps, they are not created due to failed downloading of cartopy data package. 
```
Generating TC Metrics from Obs Files
======================================
Plot saved in: /lcrc/group/e3sm/public_html/diagnostic_output/ac.zhang40/tests/v2_5_0_all_sets/tc_analysis/tc-intensity.png
total number based on 6 basins 7.2 [0.0, 3.2, 0.6, 0.1, 1.5, 1.8]
Plot saved in: /lcrc/group/e3sm/public_html/diagnostic_output/ac.zhang40/tests/v2_5_0_all_sets/tc_analysis/tc-frequency.png
Plot saved in: /lcrc/group/e3sm/public_html/diagnostic_output/ac.zhang40/tests/v2_5_0_all_sets/tc_analysis/ace-distribution.png
Plot saved in: /lcrc/group/e3sm/public_html/diagnostic_output/ac.zhang40/tests/v2_5_0_all_sets/tc_analysis/tc-frequency-annual-cycle.png
/home/ac.zhang40/y/envs/ed250/lib/python3.8/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/50m/physical/ne_50m_land.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
```

I think we should pursue the solution @xylar  pointed out here: https://github.com/E3SM-Project/e3sm_diags/issues/518#issuecomment-915360208

**Comment by forsyth2** [comment]
> I think we should pursue the solution @xylar pointed out here

I'm not finding much documentation on `cartopy_offlinedata`. Is the idea to just add it to the list of dependencies in the conda yml file? Or would it be imported in every file that imports `cartopy`?
