### ISSUE TITLE
Spurious lower tropospheric warm biases over Antarctica due to post-processing

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/e3sm_diags#522]
It has been a persistent feature since v1that substantial lower-tropospheric warm biases are present in the zonal-pressure plots.
Below is [a difference plot of v2.LR.historical ensemble versus ERA-Interim](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/wlin/E3SMv2/v2.LR.HIST_ENS/e3sm_diags/180x360_aave/model_vs_obs_1985-2014/viewer/zonal_mean_2d/era-interim/t-global-era-interim/ann.html)
![image](https://user-images.githubusercontent.com/8215478/133637646-f6753547-7702-4cca-8790-a88146ab5189.png)

[Investigation led by @zhangshixuan1987 found it is mostly an artifact of post-processing](https://acme-climate.atlassian.net/wiki/spaces/ECG/pages/3048701961/Warm+bias+in+low+troposphere+over+southern+polar+region). 

The spurious biases are due to how the zonal mean difference plots are computed. Typically zonal means are computed first for model and obs (reanalysis), separately, which are then used to compute the differences. The root cause is the reanalysis data used utilize extrapolation to fill grids at all pressure levels, including below the ground surface, while the model data only include those above surface (pressure < PS). There would be no problem when at a certain level, the model has zero valid points (as seen in the blank space below around 875 hPa). When the model has grids partially masked out for a pressure level, the data points used to compute zonal mean could be very different between model and obs, let alone the reanalysis data contain extrapolated data.

The problem can be eliminated by computing the differences between model and obs first, using consistent masks, then deriving the zonal means.

**Comment by chengzhuzhang** [comment]
Thank you @zhangshixuan1987 for a nice and thorough investigation. And thank you @wlin7 to summarize and file an issue. The proposed change seems reasonable and will reduce the selection bias with current post-processing order (computing zonal mean first for model and reanalysis and then take the difference) I will try to push in a change soon.

**Comment by wlin7** [comment]
Thank you for taking care of this issue, @chengzhuzhang .
