### ISSUE TITLE
LCRC and pre-commit (or Python 3.9?) causing BlockingIOError: [Errno 11] Resource temporarily unavailable: 

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#526]
The zppy and zstash dev envs (both Python 3.7.10) run pre-commit fine on LCRC.

The error below that is outputted through pre-commit seems to be specific to LCRC servers and Python 3.9 in thee3sm_diags_dev env. I reinstalled the latest version of the e3sm_diags dev env on LCRC, but it outputs the same error. Also, I tested the latest dev env on my local machine and it works fine.

```
BlockingIOError: [Errno 11] Resource temporarily unavailable: '/gpfs/fs1/home/ac.tvo/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-21.1.2-py3-none-any/pip/_vendor/distlib/w32.exe' -> '/gpfs/fs1/home/ac.tvo/.cache/pre-commit/repo7v9o5q3a/py_env-python3.9/lib/python3.9/site-packages/pip/_vendor/distlib/w32.exe'
```

What I suggest for now:
- Perform dev locally to check changes against pre-commit then pull those changes to test on LCRC, or use no-verify and fix the pre-commit errors that appear in the GH Actions build.

**Comment by xylar** [comment]
Moving my comment here.

I believe I've seen issues like that frequently on Chrysalis. It seems to have to do with recent versions of python and that file system. We ended up having to use slow file copying as a fallback on Chrysalis in MPAS-Analysis because of this.

**Comment by xylar** [comment]
https://github.com/MPAS-Dev/MPAS-Analysis/pull/796

**Comment by tomvothecoder** [comment]
Thanks for the info @xylar
