### ISSUE TITLE
Support a new set Pressure-Lat zonal mean zooming in Stratosphere

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#534]
Close #492 

Only show Stratosphere (i.e., above 100 hPa) with logarithmic y axis can done currently, with two method:
Specify plevs and to set `plot_log_plevs = True` in a configuration file:
```
import os
from e3sm_diags.parameter.core_parameter import CoreParameter
from e3sm_diags.parameter.zonal_mean_2d_parameter import ZonalMean2dParameter
from e3sm_diags.run import runner
import numpy
 
param = ZonalMean2dParameter()
 
param.test_data_path = '/Users/zhang40/Documents/ACME_simulations/'
param.test_name = '20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01'
param.reference_data_path = '/Users/zhang40/Documents/ACME_simulations/obs_for_e3sm_diags/climatology'
param.run_type = 'model_vs_obs'
prefix = '/Users/zhang40/Downloads'
param.seasons = ["ANN"]
param.multiprocessing = True
param.results_dir = os.path.join(prefix, 'zonal_mean_2d_test_stratos')

 
param.plevs = numpy.logspace(0, 2.0, num=10).tolist()
param.plot_log_plevs = True
 
 
runner.sets_to_run = ['zonal_mean_2d']
runner.run_diags([param])
``` 

Or use a command line, example as follows:

`e3sm_diags zonal_mean_2d --no_viewer --case_id 'MERRA2' --sets 'zonal_mean_2d' --run_type 'model_vs_obs' --variables 'T' --seasons 'ANN' --regions 'global' --regrid_tool 'esmf' --regrid_method 'conservative' --plevs '1.0' '1.6681005372000588' '2.7825594022071245' '4.641588833612778' '7.742636826811269' '12.91549665014884' '21.544346900318832' '35.93813663804626' '59.94842503189409' '100.0' --plot_log_plevs --main_title 'T ANN' --backend 'mpl' --output_format 'png' --canvas_size_w '1212' --canvas_size_h '1628' --figsize '8.5' '11.0' --dpi '150' --arrows --contour_levels '180' '185' '190' '200' '210' '220' '230' '240' '250' '260' '270' '280' '290' '295' '300' --test_name '20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01' --test_colormap 'cet_rainbow.rgb' --ref_name 'MERRA2' --reference_name 'MERRA2 Reanalysis' --reference_colormap 'cet_rainbow.rgb' --diff_title 'Model - Observation' --diff_colormap 'diverging_bwr.rgb' --diff_levels '-7' '-6' '-5' '-4' '-3' '-2' '-1' '1' '2' '3' '4' '5' '6' '7' --multiprocessing --num_workers '4' --granulate 'variables' 'seasons' 'regions' --selectors 'sets' 'seasons' --test_data_path '/Users/zhang40/Documents/ACME_simulations/' --reference_data_path '/Users/zhang40/Documents/ACME_simulations/obs_for_e3sm_diags/climatology' --results_dir '/Users/zhang40/Downloads/zonal_mean_2d_test_stratos'`
 
Users need to modify the --test_name, data paths (--test_data_path, --ref_data_path, --results_ir) , and specify the --contour_levels, --diff_levels for each variable (--variables) to optimize the look of the plots. 

But it is desired a make a new standard set with pre-defined contour levels for the Stratosphere.

**Comment by tomvothecoder** [comment]
Sounds good, thanks for the clear directions Jill.
