### ISSUE TITLE
Improvements to viewer for e3sm_diags for cmip

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#549]
Per the 1/7/22 meeting:
- Add banner with legend for realization column (and others if needed)
- Make table column headers sticky

This issue involves looking into the viewer code and seeing what CSS framework is used (if any), and how the HTML is structured. If it is simple, might be able to add a CSS attribute to make the table column headers stick as the user scrolls.

**Comment by chengzhuzhang** [comment]
Hey Tom, thanks for creating this issue. The viewer to show all CMIP results was generated by a separate script Chris developed. It is currently not included in e3sm_diags code base. I will include those scripts so that you could help enhance.

**Comment by chengzhuzhang** [comment]
Hey @tomvothecoder, the steps to generate the viewer is as follows (note you would need `jinja2` in your Python env):
```
cd /var/www/acme/acme-diags/e3sm_diags_for_cmip
python generate_page.py
```
Let me know if there is permission issue with the data. Thanks!

**Comment by tomvothecoder** [comment]
Closing this issue since we're moving away from CDP Output Viewer (#628).
