### ISSUE TITLE
Problem launching e3sm_unified/e3sm_diags on cori compute nodes

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/e3sm_diags#556]
post processing with zppy sends the jobs to compute nodes. It would immediately get the following error

craype-hugepages2M(43):ERROR:102: Tcl command execution failed: set             CRAYPE_DIR      $env(CRAYPE_DIR)

Since failure to load e3sm_unified, none of the post processing jobs can proceed.
The problem can be reproduced by requesting an interactive knl or haswell node, and source the e3sm_unified start up script
```
salloc --nodes 1 --qos interactive --time 00:30:00 --constraint haswell
source /global/common/software/e3sm/anaconda_envs/load_latest_e3sm_unified_cori-haswell.sh
```

Similar problem has been reported (and resolved) in  [Compass PR #274 ](https://github.com/MPAS-Dev/compass/pull/274#issuecomment-973029647)

**Comment by chengzhuzhang** [comment]
Hey @wlin7 for the latest official release of `e3sm_unified`, both `e3sm_diags` and `zppy` has been tested on cori-haswell, the deprecation warning was harmless. I just ran `e3sm_diags` alone and it started fine. I'm not sure why those post processing jobs won't proceed. 

Right now, @xylar has deployed a new testing environment for new  version of `e3sm_unified`, maybe it is worthwhile to try with? `source /global/common/software/e3sm/anaconda_envs/test_e3sm_unified_1.6.0rc5_cori-haswell.sh`

**Comment by xylar** [comment]
@wlin7, as far as I can tell, the "error:
```
craype-hugepages2M(43):ERROR:102: Tcl command execution failed: set CRAYPE_DIR $env(CRAYPE_DIR)
```
will also occur every time the modules used by E3SM on Cori-Haswell and Cori-KNL are loaded, it's just not displayed.  I am following the same procedure as E3SM for loading these modules.

I concur with @chengzhuzhang that that error should be harmless and if your analysis isn't working it is for another reason.

**Comment by wlin7** [comment]
Thanks for looking into this issue, @chengzhuzhang , @xylar . You are right, Tcl execution failure is not the cause.
What really matter is the failure to locate NCO (ncks for ncclimo). I thought if e3sm_unified was activated, there was no reason not able to locate ncks. That is what caused me to I incorrectly suspect that the Tcl error message prematurely ended the activation of e3sm_unified. Repeated the interactive access to a node, still seeing the error when sourcing e3sm_unified., but ok to find ncks.

Below is the full error message when using zppy to compute eam climo. I wonder if it is due to search-path setting in ncclimo. Apparently, the actual path for ncks, /global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.5.1_cori-haswell/bin,  was not in the search path.

```
 craype-hugepages2M(43):ERROR:102: Tcl command execution failed: set             CRAYPE_DIR      $env(CRAYPE_DIR)

Module Deprecation Warning: upgrade to 3.21.3 (new default on 2021-09-21)
which: no ncks in (.:/global/homes/w/wlin/bin:/global/common/software/e3sm/anaconda_envs/system/cori-haswell/e3sm_unified_1.5.1/intel/mpt/tempest_extremes_2.2/bin:/global/common/software/e3sm/anaconda_envs/system/cori-haswell/e3sm_unified_1.5.1/intel/mpt/esmf_8.1.1/bin:/global/common/sw/cray/cnl7/haswell/cmake/3.20.2/bin:/global/common/sw/cray/sles15/x86_64/git/2.21.0/gcc/8.2.0/kb7xpwq/bin:/opt/cray/pe/parallel-netcdf/1.11.1.1/bin:/opt/cray/pe/hdf5-parallel/1.10.5.2/bin:/opt/cray/pe/hdf5/1.10.5.2/bin:/opt/cray/pe/netcdf/4.6.3.2/bin:/opt/intel/compilers_and_libraries_2019.3.199/linux/bin/intel64:/opt/cray/pe/mpt/7.7.10/gni/bin:/opt/cray/pe/craype/2.6.2/bin:.:/global/homes/w/wlin/bin:.:/global/homes/w/wlin/bin:/usr/common/software/python/3.8-anaconda-2020.11/bin:/usr/common/software/python/3.8-anaconda-2020.11/condabin:.:/global/homes/w/wlin/bin:/global/common/cori/software/idl/idl85/idl/bin:/opt/cray/rca/2.2.20-7.0.1.1_4.74__g8e3fb5b.ari/bin:/opt/cray/alps/6.6.58-7.0.1.1_6.30__g437d88db.ari/sbin:/opt/cray/alps/default/bin:/opt/cray/job/2.2.4-7.0.1.1_3.55__g36b56f4.ari/bin:/global/common/cori/software/altd/2.0/bin:/usr/common/software/bin:/usr/common/nsg/bin:/opt/ovis/bin:/opt/ovis/sbin:/opt/cray/pe/modules/3.2.11.4/bin:/global/homes/w/wlin/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/cray/pe/bin)
ncclimo: ERROR Unable to find NCO, ${nco_exe} =
```

**Comment by xylar** [comment]
@wlin7, could you share your `.bashrc` or `.bashrc.ext`?  I'm wanting to see if you do some path modifications that might explain how NCO is getting confused.

Also pinging @czender to see if he has thoughts.

And if would be great to know if you still have this problem with the test E3SM-Unified 1.6.0rc5, in case the new approach there has fixed this problem.

**Comment by wlin7** [comment]
Hi @xylar , didn't expect you are still online at this time. 
My .bashrc is system default.  ~wlin/.bashrc.ext seems harmless.

Now I need to walk back my description of the issue. With the zppy generated script for computing climo, it would give me the same error message when running on login node. It was not just a problem for compute node.

**Comment by wlin7** [comment]
Xylar, tried with test E3SM-Unified 1.6.0rc5 and ran the script on login node, problem remains.

**Comment by xylar** [comment]
@wlin7, I'm at LANL right now, so still up.

Somehow you have added `.` and `/global/homes/w/wlin/bin` in your `$PATH` variable.  While that's not a problem in and of itself, I suspect that something that is adding those (e.g. an alias or something in your `.bashrc.ext`) is interfering with whatever mechanism adds the conda path to your `$PATH`.  It is missing from the list that `ncclimo` is searching for `ncks`.

**Comment by xylar** [comment]
This is something specific to how your shell is configured somehow because if all of us had this problem, `ncclimo` wouldn't have worked for any of us.

**Comment by xylar** [comment]
I suspect that the new E3SM-Unified would work for you on a compute node because NCO is now coming from Spack, not from a conda environment.  But that's not a real solution to the problem because it won't help you on a login node as you just saw.

**Comment by wlin7** [comment]
Great having you in closer time zone, Xylar!

I commented out the line of adding '.' to the path, re-login and run the script, the problem didn't go away.

Let me also try some other way of running the script from the login node. BTW, I didn't know the re-arrangement of NCO. Thanks for letting me know.

**Comment by xylar** [comment]
Hmm, okay, thanks for trying that out.

**Comment by czender** [comment]
It's kinda hilarious when an RC5 works for all the developers and breaks the first time a "real user" tries it :) Unfortunately I have no immediate ideas on the solution. @wlin7 NCO did not change, but the way it is compiled and delivered in the E3SMU environment did change. Oddly, the old method (Conda-based) now does not work for you. I hope the new method (Spack) does, but that would still leave the Conda issue unsettled...

**Comment by xylar** [comment]
Thanks @czender.  I was hoping you would have some insight.  I guess we're both baffled.

**Comment by wlin7** [comment]
Running on compute node with test E3SM-Unified 1.6.0rc5 appears to be working. Thanks Xylar, I will update the zppy config to start over.

Hi @czender, thanks for chiming in. Looks like rc5 only still not solving my problem when using on login node.

**Comment by xylar** [comment]
@wlin7, do you know that zppy worked for you (via E3SM-Unified) on Cori-Haswell previously?  Is this a new issue?

**Comment by czender** [comment]
@wlin7 All of my testing of RC5 has been from the command line, where ncclimo/ncremap work well for me both on compute and login nodes. AFAICT you are experiencing difficult running scripts generated by zppy, possibly within a queuing environment. Can you verify that those scripts source the RC5 environment from within the script? Can you point us to a script that should work (with minor modifications for writable directories) for us as well as you?

**Comment by wlin7** [comment]
Hi @czender , great it works well for you on both compute and login nodes. 
I am still having problem when running on login node.  A sample zppy generated script below.
`/global/homes/w/wlin/pe3sm/E3SM_simulations/E3SMv2/cryo/20210603.WCYCL1850.ne30pg2_ECwISC30to60E2r1.rc3e.cori-knl/post/scripts/climo_atm_monthly_180x360_aave_0150-0199.bash`
I think you have permission to run it directly thru the ncclimo step in the script.

**Comment by czender** [comment]
@wlin7 I will try to look into this soon. In the meantime, we need to know the answer to @xylar 's question above, do zppy-generated scripts provided by E3SMU 1.5.1 work for you on Cori-Haswell? Is this a new issue?

**Comment by wlin7** [comment]
Sorry @xylar , I didn't notice your last msg. When using E3SMU 1.5.1, the zppy generated script didn't work on either knl or haswell nodes. Looking back, I also had this issue back on Nov. 26, but didn't explore further at that time.

**Comment by czender** [comment]
@wlin7 Most likely this indicates an old problem that is not a new regression in E3SMU 1.6. The bash script contains this:

```
ncclimo \
--case=20210603.WCYCL1850.ne30pg2_ECwISC30to60E2r1.rc3e.cori-knl \
--jobs=${SLURM_NNODES} \
--mem_mb=0 \
--thr=1 \
--parallel=mpi \
--yr_srt=150 \
--yr_end=199 \
--input=/global/homes/w/wlin/pe3sm/E3SM_simulations/cryo/E3SMv2/20210603.WCYCL1850.ne30pg2_ECwISC30to60E2r1.rc3e.cori-knl/archive/atm/hist \
--map=/global/homes/z/zender/data/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc \
--output=trash \
--regrid=output \
--model=eam
```

I'm unclear on what you mean by RC5 works on compute nodes not login nodes.
It makes sense to me that this snippet fails on login nodes because `--parallel=mpi` requires an MPI environment which, to my understanding is not available on login nodes. However, if you submit it to a queue, then it looks like it should work. Can you clarify where the ncclimo executable is being executed? Login or compute node?

**Comment by xylar** [comment]
@czender, the issue that @wlin7 reported was originally completely unrelated to E3SM-Unified 1.6.0.  He was using 1.5.1 and was getting messages from `ncclimo` that it couldn't find `ncks` both on compute and login nodes when sourcing the activation script for E3SM-Unified 1.5.1, see above.  @chengzhuzhang asked @wlin7 to try E3SM-Unified 1.6.0rc5, just to see if that helped, and it does seem to on a compute node (where Spack is setting the paths for NCO, not conda).

It seems like the `--parallel=mpi` flag is certainly not something to be using on a login node, I completely agree but I don't think that can account for the problem unless `ncclimo` changes the path in which it searches for `ncks` based on this flag.

**Comment by czender** [comment]
@xylar I agree with your point above. And `ncclimo` does not set any paths unless explicitly asked to, which is not happening here. I submitted the script interactively on a login node and can reproduce the 
`ncclimo: ERROR Unable to find NCO, ${nco_exe} = 
`
issue that @wlin7 reports above.

**Comment by wlin7** [comment]
Exactly, @xylar, @czender. The issue I had was about locating ncks -- though I initially mistook the Tcl error as failing to fully loading E3SMU. 

As far as post-processing with zppy is concerned, my issue is considered resolved if using 1.6.0rc5, because we are expected to always send the jobs to compute nodes. It is certainly a bonus (at low priority) if the script can also run on login nodes.

**Comment by czender** [comment]
@wlin7 I have implemented a fix that works for me and @xylar has graciously agreed to roll an RC6. Please test it when available to verify it works for you. You won't need to make any changes to the way you're currently using `ncclimo`.

**Comment by xylar** [comment]
@wlin7 and @czender, there has been a delay in installing E3SM-Unified 1.6.0rc6 on Cori-Haswell: we ran out of space in the location where we install software.  I deleted all the previous release candidates and the Spack build space, and the installation is now proceeding.  You should be able to test later this evening or tomorrow (as soon as the activation script appears).

This release candidate is also deployed on Chrysalis and Anvil in case you want to test there already.  Compy is always the slowest to deploy, so testing likely won't be possible there until tomorrow.

**Comment by xylar** [comment]
E3SM-Unified 1.6.0rc6 is now available on Cori-Haswell:
```
source /global/common/software/e3sm/anaconda_envs/test_e3sm_unified_1.6.0rc6_cori-haswell.sh
```

**Comment by czender** [comment]
Thanks very much @xylar. RC6 works fine for me on Cori in the same situation @wlin7 reported that has been broken for some time.

**Comment by czender** [comment]
@wlin7 I'm ready to release NCO 5.0.6 if/when you bless it as solving the problem you ran into.

**Comment by wlin7** [comment]
Unfortunately, I am still having the problem when running on login node with RC6 (no problem on compute node)

```
(e3sm_unified_1.6.0rc6_nompi) wlin@cori02:~/pe3sm/tmp> which ncks
/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.6.0rc6_nompi/bin/ncks
(e3sm_unified_1.6.0rc6_nompi) wlin@cori02:~/pe3sm/tmp> which ncclimo
/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.6.0rc6_nompi/bin/ncclimo
(e3sm_unified_1.6.0rc6_nompi) wlin@cori02:~/pe3sm/tmp> ncclimo --case=20180215.DECKv1b_H1.ne30_oEC.edison --mem_mb=0 --thr=1 --yr_srt=1985 --yr_end=2014 \
> --input=/global/homes/w/wlin/pe3sm/E3SM_simulations/DECKv1/20180215.DECKv1b_H1.ne30_oEC.edison/archive/atm/hist \
> --map=/global/homes/z/zender/data/maps/map_ne30np4_to_cmip6_180x360_aave.20181001.nc \
> --output=trash --regrid=output --model=cam
which: no ncks in (/usr/common/software/python/3.8-anaconda-2020.11/bin:/usr/common/software/python/3.8-anaconda-2020.11/bin:/usr/common/software/python/3.8-anaconda-2020.11/condabin:/global/common/cori/software/idl/idl85/idl/bin:/opt/cray/pe/mpt/7.7.10/gni/bin:/opt/cray/rca/2.2.20-7.0.1.1_4.74__g8e3fb5b.ari/bin:/opt/cray/alps/6.6.58-7.0.1.1_6.30__g437d88db.ari/sbin:/opt/cray/alps/default/bin:/opt/cray/job/2.2.4-7.0.1.1_3.55__g36b56f4.ari/bin:/opt/cray/pe/craype/2.6.2/bin:/opt/intel/compilers_and_libraries_2019.3.199/linux/bin/intel64:/usr/common/software/darshan/3.2.1/bin:/global/common/cori/software/altd/2.0/bin:/usr/common/software/bin:/usr/common/nsg/bin:/opt/ovis/bin:/opt/ovis/sbin:/opt/cray/pe/modules/3.2.11.4/bin:/global/homes/w/wlin/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/cray/pe/bin)
ncclimo: ERROR Unable to find NCO, ${nco_exe} =

```

**Comment by wlin7** [comment]
Problem solved, @xylar, @czender .

The problem was because of a __conda_setup in my .bashrc, which was somehow automatically appended (assumingly when installing certain conda env). After commenting it out and re-login, ncclimo rans ok. Thanks for help sorting this out.

**Comment by xylar** [comment]
@wlin7, great! That is exactly the kind of thing I was looking for when I asked you to share your .bashrc above (and you said there was nothing there of interest). As you’ve learned, this autoactication of your own conda base is a big problem for us on HPC.

**Comment by wlin7** [comment]
Thanks @xylar . I missed that. I remember NERSC did not even allow user to put anything in .bashrc (use .bashrc.ext instead) -- if I manually put something there, it would be cleared next time, serving as a reminder to always use .bashrc.ext. 

BTW, does it still take RC6 to have ncclimo work on login node? @czender said above he reproduced the error I had.

**Comment by czender** [comment]
@wlin7 That's a fair question. Although I do not have any Conda activation code in my .bashrc* files, I did experience the same issue as you. I think the reason is that I never follow directions :) My .bashrc on Cori is the same as I use on all computers and I have always ignored the NERSC recommendations not to touch .bashrc. You would be horrified by my .bashrc, which has metastasized for 30 years. Presumably you and I are not the only rule-breakers so it will be good to have the RC6 code be used for E3SMU 1.6. The problem you encountered was by no means universal, yet the extra code in the fix seems harmless and will further reduce mysterious errors. This has helped me understand why sometimes, on some platforms, NCO users experience different behavior than I do. What say ye, @xylar, shall I release 5.0.6 so you can build/release 1.6.0?

**Comment by xylar** [comment]
@czender, yes, go for it!  I'm glad we solved the mystery and I agree that it doesn't hurt to try to work around issues folks might have with NCO and E3SM-Unified even if they're rare.

**Comment by wlin7** [comment]
Glad to hear there is positive outcome from this, thanks again, @czender , @xylar . I felt guilty not having spot the additional lines in my .bashrc and letting you both taking extra effort to resolve this issue. Like the way RC6 can better seal from the default user env.
