### ISSUE TITLE
Bug in 2.6.1: incomplete SST lat-lon plot

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/e3sm_diags#561]
Looks like a bug crept in between 2.6.0 and 2.6.1.

![image](https://user-images.githubusercontent.com/15743046/153637252-41e16964-77c9-4822-8a99-3c893e582b46.png)

https://portal.nersc.gov/cfs/e3sm/golaz/E3SMv2/v2.LR.historical_0111/e3sm_diags/180x360_aave/model_vs_obs_1985-2014/viewer

**Similar figure with 2.6.0**

![image](https://user-images.githubusercontent.com/15743046/153637314-08e4a682-398e-4c13-b884-815831148df8.png)

https://portal.nersc.gov/cfs/e3sm/golaz/E3SMv2/v2.LR.historical_0111/e3sm_diags/180x360_aave/model_vs_obs_1955-1984/viewer

**Comment by chengzhuzhang** [comment]
It's bad and also interesting. Looks like the SST lat-lon figures are all impacted. I will take a look.

**Comment by xylar** [comment]
☹️ How did this slip through our testing?

**Comment by chengzhuzhang** [comment]
I tried to reproduce this figure with one line:
```
e3sm_diags lat_lon --no_viewer --case_id 'SST_CL_HadISST' --sets 'lat_lon' --run_type 'model_vs_obs' --variables 'SST' --seasons 'ANN' --regions 'global' --regrid_tool 'esmf' --regrid_method 'conservative' --main_title 'SST ANN global' --backend 'mpl' --output_format 'png' --canvas_size_w '1212' --canvas_size_h '1628' --figsize '8.5' '11.0' --dpi '150' --arrows --contour_levels '-1' '0' '1' '3' '6' '9' '12' '15' '18' '20' '22' '24' '26' '28' '29' --test_name '20210528.v2rc3e.piControl.ne30pg2_EC30to60E2r2.chrysalis' --test_colormap 'cet_rainbow.rgb' --ref_name 'HadISST_CL' --reference_name 'HadISST (Climatology)' --reference_colormap 'cet_rainbow.rgb' --diff_title 'Model - Observation' --diff_colormap 'diverging_bwr.rgb' --diff_levels '-5' '-4' '-3' '-2' '-1' '-0.5' '-0.2' '0.2' '0.5' '1' '2' '3' '4' '5' --multiprocessing --num_workers '5' --granulate 'variables' 'seasons' 'plevs' 'regions' --selectors 'sets' 'seasons' --reference_data_path '/global/cfs/cdirs/e3sm/e3sm_diags/obs_for_e3sm_diags/climatology/' --test_data_path '/global/cfs/cdirs/e3sm/e3sm_diags/postprocessed_e3sm_v2_data_for_e3sm_diags/20210528.v2rc3e.piControl.ne30pg2_EC30to60E2r2.chrysalis/climatology/rgr/' --results_dir '/global/cfs/cdirs/e3sm/www/zhang40/tests_e3sm_diags_issue561/'
```
Very interesting that this incomplete figure issue is only reproduced on `cori-haswell` but not on login node. It is very strange because `e3sm_unified` has exactly same version of `matplotlib/cartopy` for both `e3sm_unified_1.6.0_nompi` and `e3sm_unified_1.6.0_cori-haswell`.

**Comment by xylar** [comment]
Are there preprocessing steps like remapping?  Could it be that the bounds of the remapped version are wrong and that's the reason?  It certainly looks like a plotting problem but it's worth checking the NetCDF data to be sure.

**Comment by chengzhuzhang** [comment]
Yeah, notice that the metrics numbers differ. So there is data problem involved. Checking more.

**Comment by chengzhuzhang** [comment]
More updates, I tried generated a code snippet trying to find source of the error. 
```
import cdms2
  

def regrid_to_lower_res(mv1, mv2, regrid_tool, regrid_method):
    """Regrid transient variable toward lower resolution of two variables."""

    axes1 = mv1.getAxisList()
    axes2 = mv2.getAxisList()

    # use nlat to decide data resolution, higher number means higher data
    # resolution. For the difference plot, regrid toward lower resolution
    if len(axes1[1]) <= len(axes2[1]):
        mv_grid = mv1.getGrid()
        mv1_reg = mv1
        mv2_reg = mv2.regrid(
            mv_grid, regridTool=regrid_tool, regridMethod=regrid_method
        )
        mv2_reg.units = mv2.units

    else:
        mv_grid = mv2.getGrid()
        mv2_reg = mv2
        mv1_reg = mv1.regrid(
            mv_grid, regridTool=regrid_tool, regridMethod=regrid_method
        )
        mv1_reg.units = mv1.units

    return mv1_reg, mv2_reg


file1 = '/global/cfs/cdirs/e3sm/www/zhang40/tests_e3sm_diags_issue561/lat_lon/SST_CL_HadISST/HadISST_CL-SST-ANN-global_test.nc'
file2 = '/global/cfs/cdirs/e3sm/www/zhang40/tests_e3sm_diags_issue561/lat_lon/SST_CL_HadISST/HadISST_CL-SST-ANN-global_ref.nc'

var1 = cdms2.open(file1)('SST')
var2 = cdms2.open(file2)('sst')

var1_reg, var2_reg = regrid_to_lower_res(var1, var2, "esmf", "conservative")
diff = var2_reg - var1_reg
outfile = 'new_diff.nc'
fout = cdms2.open(outfile, 'w')
fout.write(diff)
fout.close()
```
It turned out that the program is complaining about `esmf` is not:
```
(e3sm_unified_1.6.0_cori-haswell) chengzhu@nid00807:/global/cfs/cdirs/e3sm/www/zhang40/tests_e3sm_diags_issue561/lat_lon/SST_CL_HadISST> srun python issue_561.py 
/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.6.0_cori-haswell/lib/python3.9/site-packages/cdms2/avariable.py:1289: Warning: 
avariable.regrid: regridTool = 'esmf' but your version does not
seems to be built with esmf, will switch to regridTool = 'libcf'
```
Running on login node doesn't have this issue. And it seems like `ESMF` package is not included in `cori-haswell`.

**Comment by xylar** [comment]
@chengzhuzhang, ESMF was one of the packages I built with spack and removed from the conda environment on compute nodes.  This needs to be fixed somehow so cdms2 looks for ESMF in the path, ot in the conda environment.  ESMF should be in the path unless the call you are making is re-initializing the path somehow.

**Comment by xylar** [comment]
This was the kind of thing that we did 5 weeks of testing in the hopes of catching.  I'm really sad this slipped through.

**Comment by chengzhuzhang** [comment]
Image checker was supposed to catch this type of image change. But that was only required to run with e3sm_diags 's integration test and complete tests. I think we should do a similar check with e3sm_unified release as well.

**Comment by xylar** [comment]
Okay, I think I understand.  I didn't realize that `cdms2` relied on `esmpy`.  None of our other packages use `esmpy` as far as I know.

The approach where we have ESMF as its own program works great if folks are calling `ESMF_RegridWeightGen` from the command line.  That's what NCO and MPAS-Analysis do.  But `cdms2` uses the python bindings so it needs the conda version of ESMF to go with ESMPy.

I think the solution isn't too hard.  I need to *not* uninstall `esmf` from the conda environment.  That will mean that there are 2 version of `ESMF_RegridWeightGen` in the path, but the Spack version should take priority.  I was just getting rid of the conda version as a precaution.

I will need to re-deploy E3SM-Unified on all the machines with Spack (which is luckily only 5) once I fix this.

Sorry for making a fuss.

> Image checker was supposed to catch this type of image change. But that was only required to run with e3sm_diags 's integration test and complete tests. I think we should do a similar check with e3sm_unified release as well.

I think some kind of a check like this is important.  I don't know how successful an automated check will be unless you have a reference that uses the same packages as E3SM-Unified.

**Comment by chengzhuzhang** [comment]
There is a permission issue:
```
chengzhu@nid00803:~> source /global/common/software/e3sm/anaconda_envs/load_latest_e3sm_unified_cori-haswell.sh
bash: /global/common/software/e3sm/anaconda_envs/spack/spack_for_mache_1.2.0/share/spack/setup-env.sh: Permission denied
If 'spack' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf spack
craype-hugepages2M(43):ERROR:102: Tcl command execution failed: set             CRAYPE_DIR      $env(CRAYPE_DIR)

Module Deprecation Warning: upgrade to 3.21.3 (new default on 2021-09-21)
```

**Comment by xylar** [comment]
I see. I thought it would work before permissions finished updating.  Obviously not. It should be done now.

**Comment by chengzhuzhang** [comment]
Global SST figure is now completed :)
Thank you so much for a super quick turnaround.
