### ISSUE TITLE
Update documentation on testing

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#564]
Update documentation on testing: On https://e3sm-project.github.io/e3sm_diags/_build/html/master/dev_guide/testing.html,
```
mv all_sets_results /lcrc/group/e3sm/public_html/e3sm_diags_test_data/integration/expected/integration_test_images
```
should instead be
```
mv tests/integration/all_sets_results_test /lcrc/group/e3sm/public_html/e3sm_diags_test_data/integration/expected/integration_test_images
```

The `tests/integration` change is because of #544 (specifically https://github.com/E3SM-Project/e3sm_diags/pull/544/files#diff-dad7b84674fccc140b0fb2f17af742872a2f5cda5ddd36af501f39b404baf0cbR26 -- `command='python -m unittest tests/integration/'`).

Unclear why the docs currently call to move `all_sets_results` rather than `all_sets_results_test`.

**Comment by chengzhuzhang** [comment]
Resolved by #551
