### ISSUE TITLE
Add Q to zonal_mean_2d_stratosphere set

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#568]
https://compy-dtn.pnl.gov/tang338/E3SM/v2/final/20211229.O3eqO3LNZ.chemUCI_Linozv3/e3sm_diags/180x360_aave/model_vs_obs_2000-2009/viewer/zonal_mean_2d_stratosphere/index.html
Note:
Specific humidity from ERA-Interim and MERRA2 needs to be added to current obs sets.
Use units ppm instead of kg/kg.

**Comment by tangq** [comment]
@chengzhuzhang , thanks for opening this request.

**Comment by chengzhuzhang** [comment]
Resolved by #569
