### ISSUE TITLE
Test `e3sm_diags` 2.7.0 build with the latest version of `xarray`

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#583]
Per Xylar's request, we should test `e3sm_diags` with the latest verison of `xarray` since we ran into issues with it before (I think it was those xarray warnings?).

**Comment by chengzhuzhang** [comment]
I think we had issue with dask, but not xarray. I think it is a good idea anyway if we are shooting for converting to xcdat/xarray for the next major release.
