### ISSUE TITLE
Add lat-lon driver for MOSART (river component) variables

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#590]
Hey @jenniferholm and @dmricciuto  , FYI the lat-lon driver for ELM has been generated through #585 I'm creating this issue for MOZART variables.

**Comment by jenniferholm** [comment]
@chengzhuzhang - great, thanks for getting this started.  For reference the land river component is called "MOSART" with an "s". 

Here is the list of MOSART specific outputs, that come from the MOSART history files -  (@hydrotian - did I miss any outputs?) 

RIVER_DISCHARGE_OVER_LAND_LIQ
FLOODED_FRACTION
WRM_STORAGE
WRM_IRR_DEFICIT
WRM_IRR_DEMAND
WRM_IRR_SUPPLY
FLOODPLAIN_FRACTION
FLOODPLAIN_VOLUME

**Comment by hydrotian** [comment]
No I think these are all we need for now. Thanks to both of you!

**Comment by chengzhuzhang** [comment]
@jenniferholm Thank you for catching the miss-spelling..
And thank you for confirming the variable list @hydrotian.

**Comment by chengzhuzhang** [comment]
@hydrotian Hey Tian, I'm making progress on the river variables. Could you share some sample MOSART output, preferably the seasonal/annual mean climatology files pre-processed with NCO? Also, do you have suggestions on any unit change, or contour levels to be specified to visual these variables...i.e. preprocessing steps for plotting these variables.

**Comment by chengzhuzhang** [comment]
Hi Tian, yes, if possible please share with me a copy of seasonal/annual mean climatology files that include those requested variables. e3sm_diags could read in monthly files and generate climo on the fly. But it is more efficient to work with climo files, which is also consistent with the application of other components output. Thank you for helping out on this!

**Comment by chengzhuzhang** [comment]
@hydrotian  no worries, i was out for a good part of May as well..
thanks for sending out the files, the data format (from cdo) is a bit different than nco processed files that e3sm_diags works with. I should have explicitly mention it. I can try using nco to generate the same datasets but in a different format. I will let you know if I need further help.

**Comment by chengzhuzhang** [comment]
@hydrotian it looks like the only variable available available in a standard run for mosart is `RIVER_DISCHARGE_OVER_LAND_LIQ`
To test on the rest of the variables listed here https://github.com/E3SM-Project/e3sm_diags/issues/590#issuecomment-1126966048 I will have to get a more updated mosart output. Would you point me the newer mosart model contains these variables? Thanks.

**Comment by hydrotian** [comment]
@chengzhuzhang You might try the spinup results Qing simulated with the new water management features turned on: /compyfs/zhuq283/e3sm_scratch/E3SMv2/20220321_CBGCv2.r05.compy.I1850GSWCNPWFM.adsp/run/
