### ISSUE TITLE
Add CMIP6 comparison for AMIP data

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#596]
Support a second CMIP6 comparison box whisker figure but for AMIP runs.

**Comment by chengzhuzhang** [comment]
@tangq Hey Qi, just to follow-up, I'm in the process of looping over all the AMIP runs, but it looks like this feature will be delayed a tad, and may not be able to make the upcoming release...

**Comment by tangq** [comment]
@chengzhuzhang , thanks for the update. I got the script from Chris and can create the amip figure on cori. It is nice to have this figure in e3sm_diags in the future (but not urgent at this moment).

**Comment by chengzhuzhang** [comment]
That's good to know. If this were not making to this release, we can have a minor release and a development environment of e3sm_diags that can be activated by zppy.
