### ISSUE TITLE
Issues and enhancement for diurnal cycle precipitation plot 

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#602]
It was discovered by @wlin7 that there is some possible inconsistence in the TRMM diurnal climatology that included in E3SM Diags. In E3SM Diags, the diurnal climatology was pre-computed using ncclimo, it was noted that the 3hourly TRMM 3B42 data are provided at nominal hours, UTC 0, 3, 6, ... 21. While the time are positioned at at UTC 1.5 4.5, 7.5, ... 22.5 after ncclimo. It appears that the final precipitation phase map derived from the FFT analysis was sensitive to shifted hours. By shifting 1.5 hour back, the TRMM figure would match closely to an earlier publication by Xie et al. 2019 Figure 12. 

TODO:
 It is suggested by Shaocheng to support adjusting the color scale based on user input, to enable add more contrast in phase map if needed. 
During the investigation, I found a bug in e3sm_diags code that would slightly shift the diurnal cycle (i.e.,0.5 hours) if time is not positioned on integer hours. 
@czender is examining the ncclimo routine.

**Comment by czender** [comment]
I have gotten as far as suspecting that the shift may be due to the assumption that ncclimo makes that times are encoded using the CESM/E3SM convention where times refer to the end of the timestep. This may take some time to untangle...

**Comment by chengzhuzhang** [comment]
yes, I was thinking in the same line. I guess it is not urgent, since Cheng Tao already has a version that she manually adjusted TRMM climo diurnal by 1.5 hour. I can probably use Cheng's version until there is an NCO fix.

**Comment by chengzhuzhang** [comment]
Resolved by #603
