### ISSUE TITLE
Remove `cdtime` as a library dependency

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#615]
`cdtime` is only directly imported in `analysis_data_preprocess` scripts.

There is already a dedicated step for creating an environment specifically for preprocessing:
https://github.com/E3SM-Project/e3sm_diags/blob/e15610c8bc74daa14a37fd9bce07520718a50a7b/analysis_data_preprocess/README#L3

It can be removed as a library dependency easily.
[/conda-envs](https://github.com/E3SM-Project/e3sm_diags/tree/master/conda-env)

**Comment by chengzhuzhang** [comment]
closed by #627
