### ISSUE TITLE
suggestions on improving pressure-lat zonal mean specific humidity plots

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/e3sm_diags#636]
For the pressure-lat zonal mean specific humidity plots, e.g., [this one](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zke/20221130.production.NGD_v3atm.chem-only.H2OTEST.amip.chrysalis/e3sm_diags/180x360_aave/model_vs_obs_1985-2014/viewer/zonal_mean_2d/era5/q-global-era5/ann.html). 

- It makes more sense to add the relative difference plot besides the existing absolute difference plot because of the value range of variable "Q". This will help understand its impact on heating rate and temperature. For instance, the [200-hPa T bias](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zke/20221130.production.NGD_v3atm.chem-only.H2OTEST.amip.chrysalis/e3sm_diags/180x360_aave/model_vs_obs_1985-2014/viewer/zonal_mean_2d/era5/t-global-era5/djf.html) is largely due to the relative water vapor change at that region, which doesn't show at all on the current plot.
- With the new interactive chemistry for E3SMv3, the water vapor variable passing to radiation will be "H2OLNZ" instead of "Q". It's worth adding another H2OLNZ plot in parallel to the Q plot.

**Comment by chengzhuzhang** [comment]
Hey @tangq Thank you for bringing this important issue up. 
- For field like specific humidity which has this sharp change in vertical profile, it is indeed more useful to look at the relative difference. I will look into how to have a co-herent way to add additional relative difference plot. For a quick solution, I can add more contour levels in small values for this specific Q plot. 
- Thanks for the heads up on variable name change. Just need clarification that are both H2QLNZ and Q will be included in the standard output or H2QLNZ replaces Q?

**Comment by tangq** [comment]
It might be easier to add the relative Q plot as a separate row at [this level](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xie7/E3SMv2/20220914.PAN.MZThet.v2.LR.bi-grid.amip.chemUCI_Linozv3/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_1990-2013/viewer/zonal_mean_2d/index.html). It is useful to have the absolute diff of Q in the troposphere.

Similarly for H2OLNZ, I'd suggest adding a separate row (Maybe call it "H2OLNZ (radiation)").

H2OLNZ won't replace Q. When H2OLNZ is defined in the simulation, both H2OLNZ and Q will be saved on the h0 tape by default.
