### ISSUE TITLE
AttributeError: module 'MV2' has no attribute 'float'

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#649]
This error is seen when the development environment is installed. 
```
Traceback (most recent call last):
  File "/home/ac.zhang40/y/envs/edv290/lib/python3.10/site-packages/e3sm_diags/e3sm_diags_driver.py", line 293, in run_diag
    single_result = module.run_diag(parameter)
  File "/home/ac.zhang40/y/envs/edv290/lib/python3.10/site-packages/e3sm_diags/driver/zonal_mean_2d_driver.py", line 155, in run_diag
    mv1_p = utils.general.convert_to_pressure_levels(
  File "/home/ac.zhang40/y/envs/edv290/lib/python3.10/site-packages/e3sm_diags/driver/utils/general.py", line 117, in convert_to_pressure_levels
    mv_p = hybrid_to_plevs(mv, hyam, hybm, ps, plevs)
  File "/home/ac.zhang40/y/envs/edv290/lib/python3.10/site-packages/e3sm_diags/driver/utils/general.py", line 142, in hybrid_to_plevs
    var_p = cdutil.vertical.logLinearInterpolation(
  File "/home/ac.zhang40/y/envs/edv290/lib/python3.10/site-packages/cdutil-8.2.1-py3.11.egg/cdutil/vertical.py", line 221, in logLinearInterpolation
    Pabv = MV2.ones(sh2, MV2.float)
AttributeError: module 'MV2' has no attribute 'float' 
```
I thought it was related to `numpy` remove `np.float` in new versions (1.24) But my current env uses numpy v1.22.

**Comment by xylar** [comment]
@chengzhuzhang, I ran into that on conda-forge and patched `cdms2` to fix it, see:
https://github.com/conda-forge/cdms2-feedstock/pull/81
Could you see what version of `cdms2` (and other cdat packages) you're getting with `mamba list`?

**Comment by xylar** [comment]
@chengzhuzhang, I think I see.  I removed the `float` attribute of `MV2`, which was coming from `numpy` because of the numpy issue.  But I didn't realize that `cdutil` also needs to be patched to remove that attribute.  What a mess!

**Comment by chengzhuzhang** [comment]
Hey @xylar ! Thanks a lot for fixing things in the cdat side! 
Here's the version and build numbers of a few cdat packages:
cdat_info                 8.2.1              pyhd8ed1ab_2    conda-forge
cdms2                     3.1.5           py310h5f4584e_15    conda-forge
cdp                       1.7.0              pyhd8ed1ab_1    conda-forge
cdtime                    3.1.4           py310h1a17f1e_7    conda-forge
cdutil                    8.2.1              pyhd8ed1ab_2    conda-forge

I do notice some of them has build numbers increased compare to what available in e3sm_unified.

**Comment by xylar** [comment]
Here's a PR to fix that:
https://github.com/conda-forge/cdutil-feedstock/pull/21

**Comment by xylar** [comment]
Give it an hour or so, then try making a new environment or just updating `cdutil`. It could be that there are other problem areas to patch that I didn't find (e.g. in other packages) but I hope we got `cdutil` fixed at least.

**Comment by chengzhuzhang** [comment]
Thank you so much... I will try and report back.

**Comment by chengzhuzhang** [comment]
It looks like we need another patch cause [cdutil/vertical] also needs it(https://github.com/CDAT/cdutil/tree/314c565bc2e0d2c15d233320dc4c5496a602479a/cdutil/vertical.py
I'm not sure how best to search through GitHub to get complete instances that need to be patched. But it seems like vertical.py needs it other than time.py. Sorry for the miss in the code review last time.

**Comment by xylar** [comment]
Sorry about that!
https://github.com/conda-forge/cdutil-feedstock/pull/22

**Comment by xylar** [comment]
Okay, let's see now this goes.  I hope we got it.

**Comment by chengzhuzhang** [comment]
It works this time. Thank you, @xylar !

**Comment by xylar** [comment]
Sure!  Glad to help, especially when it's relatively easy like this.  Still, I'll be almost as happy as you when you all can drop the cdat packages...

**Comment by chengzhuzhang** [comment]
> Sure! Glad to help, especially when it's relatively easy like this. Still, I'll be almost as happy as you when you all can drop the cdat packages...

Yes! Concentrated effort is happening for migrating towards xcdat. Tom has being scopping out the work needed and started to implement...
