### ISSUE TITLE
QBO mvm generation bug?

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/e3sm_diags#719]
Currently, there is no clean way to generate QBO mvm plots. This was brought to my attention because I was curious about the QBO in conversation with @whannah1. 

The problem is that most mvm logic relies on climo-type files, but QBO must use time-series-type files. So, we either need to automatically correct the reference/test file paths or we can allow the user to set different file paths for different subtasks/plots.

![](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.ngmahfouz/E3SMv3_dev/misc/wh/qbo/QBO-model-vs-model/qbo_diags.png)

**Comment by chengzhuzhang** [comment]
Hi @mahf708 thanks for submitting this issue. I'm wondering if this is a duplicate issue but in the zppy repo: https://github.com/E3SM-Project/zppy/issues/471
For e3sm_diags itself, for model vs model comparison, the users can set different file paths: example

    qbo_param = QboParameter()
    qbo_param.reference_data_path = "ref model name"
    qbo_param.test_data_path = "test model name"
