### ISSUE TITLE
Aerosol buget metrics htmls got missing if `aerosol_budget` was listed before `lat_lon` set

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/e3sm_diags#738]
1. [There are several zppy configs in this folder](https://github.com/E3SM-Project/SimulationScripts/tree/master/archive/awg/v3dev/v3alpha04)
2. Their corresponding outputs are [here](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.ngmahfouz/E3SMv3_dev/20230918.v3alpha04.F2010.4K.chrysalis/), [here](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.ngmahfouz/E3SMv3_dev/20230918.v3alpha04.F2010.PI.chrysalis/), and [here](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.ngmahfouz/E3SMv3_dev/84e5056-smb1.pd.chrys/e3sm_diags/atm_monthly_180x360_aave_mvm/) 
3. If you look at the aerosol budget component in the viewer, you won't find it (e.g., "ANN"). But it is clearly there if you look at the raw files outside he viewer. This applies to both mvm and model-vs-obs
4. Another interesting thing is that the viewer layout has changed a bit (see screenshot)

--

![Screenshot 2023-10-03 at 8 26 16 AM](https://github.com/E3SM-Project/e3sm_diags/assets/122953255/05fd7565-7dce-4841-a9c4-35f48ce562f6)

**Comment by chengzhuzhang** [comment]
This is on my todo list. And thanks for submitting this issue. It is strange that the metrics tables were not linked correctly. This problem was not shown in my recent stand alone e3sm_diags tests for e3sm_unified release. I'm looking at the zppy files to see if there are some config caused this problem.

**Comment by chengzhuzhang** [comment]
well, chrysalis and anvil are under maintenance. I will try reproduce after they come back.

**Comment by chengzhuzhang** [comment]
thanks for providing more one data point. I tried to run stand alone e3sm_diags to reproduce on Perl-mutter with a testing dataset, with no success. It seems like the htmls that supposed to host those metrics .csv files were not generated in your and Xue's cases. I will try later on chrysalis with the zppy configs provided.

**Comment by chengzhuzhang** [comment]
@mahf708 No related to the issue mentioned, just to note that I found that in two of the zppy configuration files: 20230918.v3alpha04.F2010.PI.chrysalis.cfg and 20230918.v3alpha04.F2010.4K.chrysalis. The `short_name` was not consistent with the casename.

**Comment by chengzhuzhang** [comment]
I think I know what is going on. The `aerosol_budget` and `lat_lon` sets viewers have a conflict that if the folder generated by `aerosol_budget`, that containing these budget metrics htmls would be purged by the `lat_lon` set viewer, if `lat_lon` viewer is generated after `aerosol_budget`. 

I will try to come up with a fix. But at the time being, the workaround is to always list `lat_lon` first. 
[lat_lon first](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zhang40/E3SMv3_dev_lat_aerosol/20230918.v3alpha04.F2010.PI.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer/) vs  [aerosol_budget](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zhang40/E3SMv3_dev_aerosol_lat/20230918.v3alpha04.F2010.PI.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0002-0011/viewer/) first.

Example: 
sets = 'lat_lon', 'aerosol_aeronet', 'aerosol_budget', 'annual_cycle_zonal_mean', 'cosp_histogram', 'meridional_mean_2d', 'polar', 'zonal_mean_2d', 'zonal_mean_2d_stratosphere', 'zonal_mean_xy',

This will fix the viewer layout change. 

I think there was a change in zppy that caused the default sets to order differently in the new version.

**Comment by chengzhuzhang** [comment]
Thank you for confirming! I will update the title and keep this issue open.
