### ISSUE TITLE
[Bug]: Typo in figure titles

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/e3sm_diags#751]
### What happened?

It should be "zonal" instead of "zonel" in the figure tiltes. For example,

https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.jwolfe/E3SMv3_dev/20231020.v3alpha04_trigrid_ECwISC30to60E3r2.piControl.chrysalis/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0001-0100/viewer/annual_cycle_zonal_mean/variable/sco-omi-mls/plot.html

### Environment

N/A

**Comment by chengzhuzhang** [comment]
It looks like the typo appears in three places throughout.. Thank you for reporting @tangq

**Comment by tangq** [comment]
I was a bit surprised that we didn't notice this sooner. I noticed it as I was trying to use the figure for a slide. Should be an easy fix.

**Comment by chengzhuzhang** [comment]
Yep, I will get the fix in this afternoon.
