### ISSUE TITLE
[Bug]: `tests/integration/test_diags.py` is failing on local `main` branch

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#758]
### What happened?

6/18 tests in the image diff checker (`test_diags.py`) fail on a local copy of the `main` branch. It doesn't happen on GitHub Actions though ([example](https://github.com/E3SM-Project/e3sm_diags/actions/runs/7053488875/job/19200629424)). @forsyth2 mentioned 4 of those are also failing for him his [comment](https://github.com/E3SM-Project/e3sm_diags/pull/749#issuecomment-1813216939).

I've pasted the sections of the logs and image diffs below.

### What did you expect to happen? Are there are possible answers you came across?

Tests should pass. Maybe the plots need to be updated on Chrysalis?

### Relevant log output

```bash
============================== short test summary info ==============================
FAILED tests/integration/test_diags.py::TestAllSets::test_lat_lon_plot_diffs - AssertionError: assert 1 == 0
FAILED tests/integration/test_diags.py::TestAllSets::test_lat_lon_regional_plot_diffs - AssertionError: assert 1 == 0
FAILED tests/integration/test_diags.py::TestAllSets::test_polar_plot_diffs - AssertionError: assert 1 == 0
FAILED tests/integration/test_diags.py::TestAllSets::test_qbo_plot_diffs - AssertionError: assert 1 == 0
FAILED tests/integration/test_diags.py::TestAllSets::test_streamflow_plot_diffs - AssertionError: assert 1 == 0
FAILED tests/integration/test_diags.py::TestAllSets::test_zonal_mean_2d_plot_diffs - AssertionError: assert 1 == 0
```

### Environment

Latest `main` branch of e3sm_diags and `dev.yml` environment

### Difference in Metrics

First image is `main`, second image is LCRC, third image is the diff.

#### Lat Lon Regional
![ERA-Interim-T-850-ANN-CONUS_RRM_actual](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/c6bf7cb4-ccd9-44dc-b39f-9635a27a478d)
![ERA-Interim-T-850-ANN-CONUS_RRM_expected](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/aa033ed8-5861-411d-9cd9-91ab004bd7dd)
![ERA-Interim-T-850-ANN-CONUS_RRM_diff](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/e547ff03-e89c-429b-a79c-c5faf9a7f902)

#### Lat Lon Global
![ERA-Interim-T-850-ANN-global_actual](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/57ac2c05-ae5b-4466-8f07-f6364bb29a8a)
![ERA-Interim-T-850-ANN-global_expected](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/b1ff9779-0572-4f9b-b259-151502f2aa3f)
![ERA-Interim-T-850-ANN-global_diff](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/ff12de62-fdda-46d1-9311-4471c14c01b2)

#### Polar
![ERA-Interim-T-850-ANN-polar_S_actual](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/76c9a34a-64ca-4a0a-8b35-b13c711d3b80)
![ERA-Interim-T-850-ANN-polar_S_expected](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/6b864aad-f5ce-41d8-a185-c9711188dd8b)
![ERA-Interim-T-850-ANN-polar_S_diff](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/5498105c-9ab1-4a60-a95e-d7ab702ae28f)

#### Zonal Mean 2D
![ERA-Interim-T-ANN-global_actual](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/6df379c0-b135-4c74-a468-9e69e5cf1b4a)
![ERA-Interim-T-ANN-global_expected](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/12abece4-aa9d-417e-a96a-8cc5e8aef3b0)
![ERA-Interim-T-ANN-global_diff](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/a5a667f2-9a92-4311-a954-d88b76a2d355)

### qbo 
![qbo_diags_actual](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/b60a5670-1333-47ac-972d-044d921f79cf)
![qbo_diags_expected](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/f3a88481-a6da-4fd4-b9f3-49471247d2e6)
![qbo_diags_diff](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/3a0eb7a2-f664-47e2-8fab-9a919016930d)

### streamflow

![seasonality_map_actual](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/bcda475f-4375-415f-b76a-588d56a9d7f7)
![seasonality_map_expected](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/aa886650-4f61-4f13-8849-d3fff60ceb0e)
![seasonality_map_diff](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/dfc2a645-6129-4aaf-bbfa-6a4ed082aa03)

**Comment by tomvothecoder** [comment]
Just an FYI @forsyth2 and @chengzhuzhang. I think the images on Chrysalis need to be updated. Any thoughts?

**Comment by tomvothecoder** [comment]
@chengzhuzhang The first image is main (actual) and second image is LCRC (expected). We can talk about it at our CDAT migration sprint meeting on Monday.

**Comment by forsyth2** [comment]
> Maybe the plots need to be updated on Chrysalis?

Almost certainly the case. That said, the ultimate solution is really #756. 

Before the image diff test was introduced, what we would do is just constantly check the plots randomly to see if they looked alright. That wasn't anywhere near thorough enough, so automating an image diff check seemed like a clever idea.

As we have seen though, the image diff test is _extremely_ sensitive to noise -- thus requiring constant updates that aren't really necessary. Manual checking isn't sensitive enough and the automated check is too sensitive.

It seems like the metrics check will be both faster and exactly the level of sensitivity we want.

(Although as @chengzhuzhang pointed out, it does look like some metrics changed. That could very well be an expected change because of a pull request, one that didn't have the expected files updated after merging.)

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang The first image is main (actual) and second image is LCRC (expected). We can talk about it at our CDAT migration sprint meeting on Monday.

This is actually good news. The first images look more reasonable. Yes, let's walk it through on Monday. Thanks!

**Comment by tomvothecoder** [comment]
Next steps
- [ ] Look at commit on Chrysalis for expected results -- investigate why changes are appearing

**Comment by tomvothecoder** [comment]
- [ ] Update `qbo` and `streamflow` plots on LCRC
  - I ran the integration test on Chrysalis this time around and I get two additional test failures: `qbo` and `streamflow`. Both are because the test name differs ("e3sm_v1" for main and "system tests" for LCRC).

### qbo
![qbo_diags_actual](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/b60a5670-1333-47ac-972d-044d921f79cf)
![qbo_diags_expected](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/f3a88481-a6da-4fd4-b9f3-4
![qbo_diags_diff](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/3a0eb7a2-f664-47e2-8fab-9a919016930d)
9471247d2e6)


### streamflow

![seasonality_map_actual](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/bcda475f-4375-415f-b76a-588d56a9d7f7)
![seasonality_map_expected](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/aa886650-4f61-4f13-8849-d3fff60ceb0e)
![seasonality_map_diff](https://github.com/E3SM-Project/e3sm_diags/assets/25624127/dfc2a645-6129-4aaf-bbfa-6a4ed082aa03)
