### ISSUE TITLE
aerosol budget table values are erroneously scaled by 1e6

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/e3sm_diags#804]
### What happened?
@yunpengshan2014 reported in an E3SM Diags run with a recent v3 simulation. There are spurious values present for burden and lifetime in aerosol budget table, example: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.yshan/E3SMv3integration/E3SMv3b02_MG2P3tests/run.20231110.v3b01-Gustiness-x6tP3v2.F20TR/lat_lon_demo/viewer/table/run.20231110.v3b01-Gustiness-x6tP3v2.F20TR.chrysalis-ANN-budget-table.html

Because in PR #763, an effort was made to present the burden quantities with better units by scaling them by 1e6 ([see this](https://github.com/E3SM-Project/e3sm_diags/pull/763/files#diff-ecfefeb6c7e5dcd7a3889c33654ddd64553a417e0e4279bc3164b25e3f970064R2102)), the aerosol budget table was reading such variables that have been already "derived" and edited ([see this](https://github.com/E3SM-Project/e3sm_diags/pull/682/files#diff-9a0d2a16626af60b6f100175f4e970493fbd201a3c157bade1d2938ccf093f30R32)).

### What did you expect to happen? Are there are possible answers you came across?

N/A

### Minimal Complete Verifiable Example (MVCE)

N/A
```python
```

### Relevant log output

N/A
```python
```

### Anything else we need to know?

A fix is proposed in #805.

### Environment

N/A (eyeballed it based on user reports and conversation with @chengzhuzhang)

**Comment by chengzhuzhang** [comment]
@mahf708 thank you so much for a quick diagnosis! I just included the link to the table Yunpeng provided as a reference.
