### ISSUE TITLE
[Bug]: `AOD_550` not added to `annual_cycle_zonal_mean` `.cfg` files

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#852]
### What happened?

In PR #669, the test `.cfg` script includes the following variable for testing:

```cfg
[#]
sets = ["annual_cycle_zonal_mean"]
case_id = "AOD_550"
variables = ["AODVIS"]
ref_name = "AOD_550"
reference_name = "AERONET-composite AOD"
test_colormap = "Oranges"
reference_colormap = "Oranges"
diff_colormap = "BrBG_r"
contour_levels = [0., 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2]
diff_levels = [-0.5, -0.4, -0.3, -0.2, -0.1, -0.05, -0.02, 0.02, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5]
```

I did not find this in the `annual_cycle_zonal_mean_model_vs_obs.cfg` file.

### Environment

Latest `main` and `cdat-migration-fy24`

**Comment by tomvothecoder** [comment]
@chengzhuzhang Was this variable supposed to be added? I'm running the run all script in PR #846 but it doesn't generate this file for comparison to `main`.

**Comment by chengzhuzhang** [comment]
No. This entry needs to be retired.

**Comment by chengzhuzhang** [comment]
In this case, I guess this issue can be closed?

**Comment by tomvothecoder** [comment]
Thank you for clarifying! Yes, it can be closed.
