### ISSUE TITLE
[Bug]: stratospheric water vapor (H2OLNZ) figure is not generated

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/e3sm_diags#867]
### What happened?

The stratospheric water vapor (H2OLNZ) figure is not generated in the zonal_mean_2d_stratosphere set. This is particularly important for E3SMv3 simulations because stratospheric water vapor was changed to H2OLNZ from Q.

### Environment

See details on https://acme-climate.atlassian.net/wiki/spaces/CM/pages/4182474754/v3.LR.historical+ensemble

**Comment by rljacob** [comment]
What is the difference between H2OLNZ and Q?

**Comment by chengzhuzhang** [comment]
@tangq provide some context earlier for me to understand:

In v3, we implemented the Linoz v3 scheme that includes the stratospheric water vapor source from methane oxidization. The variable is called “H2OLNZ” and it equals to Linoz v3 water vapor (in stratosphere) and Q (in troposphere). The radiation code was also changed accordingly to use “H2OLNZ” for their calculations (i.e., specified by rad_climate).

H2OLNZ and Q only differ in stratosphere.

**Comment by tangq** [comment]
That's right, @chengzhuzhang .

**Comment by rljacob** [comment]
Doesn't the water vapor from methane oxidation get added to Q?  Or is it tracked separately?

**Comment by chengzhuzhang** [comment]
> Doesn't the water vapor from methane oxidation get added to Q? Or is it tracked separately?

pinging @tangq ...
