### ISSUE TITLE
Discussion about use of https://web.lcrc.anl.gov/ in CI

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#900]
We have been getting downloads throttled by LCRC on https://web.lcrc.anl.gov/ because we use too much bandwidth.  This is affecting research.

We should seek alternatives to https://web.lcrc.anl.gov/ in our CI, e.g.:
https://github.com/E3SM-Project/e3sm_diags/blob/ca41b0e5d913610c88410928951f1ed11c75663f/tests/integration/download_data.py#L89

**Comment by xylar** [comment]
@mahf708, do you have suggestions (e.g. containers) that we could use for e3sm_diags instead of downloading directly from the LCRC server?

**Comment by xylar** [comment]
We are seeing time-outs in https://github.com/conda-forge/e3sm_diags-feedstock/pull/38, which are likely to cause ongoing trouble building conda packages.

**Comment by xylar** [comment]
I was able to get CI to pass on https://github.com/conda-forge/e3sm_diags-feedstock/pull/38 after restarting 3 times.

**Comment by xylar** [comment]
After 8 attempts, I was finally able to get the conda package to build.  Needless to say, this is not sustainable.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1086951&view=logs&j=c1df603f-8689-50eb-30e7-21f597a4c2a3&t=e484c5e5-b8bf-5dcd-d19a-a6e998d41ead

**Comment by chengzhuzhang** [comment]
@xylar yes, this now became an outstanding issue, and we should find alternatives for hosting data needed for CI. Does mpas-analysis has a similar need or it is handled differently?


@mahf708 it looks like the container repo, you already have codes for data from input data directory, it sounds like we can just mimic it to add the diagnostics data.

**Comment by xylar** [comment]
@chengzhuzhang, this issue doesn't affect MPAS-Analysis because we don't try to do anything so sophisticated in CI.  I still run tests manually on Chrysalis as needed.

**Comment by tomvothecoder** [comment]
I had a inclination that running the GH Actions build with Python 3.9-3.12 while simultaneously downloading the same data for each run would throttle LCRC. We can make GH Actions only run when a PR is marked as ready for review if a short-term solution is needed.
 
A possible alternative solution that was mentioned before is to cache the diagnostic data on GitHub Actions, then updating the cache if updated diags data on LCRC is detected.

**Comment by xylar** [comment]
I think we really need to make it forbidden to download files from LCRC in CI.  It's badly affecting our ability to do other work.

**Comment by xylar** [comment]
So I think even if we allow it in fewer circumstances, it's still not good enough.

**Comment by tomvothecoder** [comment]
@xylar Makes sense to me. 

@mahf708 Let me know if you'd like me to test it out with e3sm_diags when it is ready.

**Comment by rljacob** [comment]
Yes the PR testing that might run several times a day on cloud resources should not be downloading lots of data.  "lots" is somewhat subjective.
